// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/pdmodel/common/PDMetadata.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Pdmodel.Common;

public class PDMetadata : global::DripSharp.PdfCarton.Pdmodel.Common.PDStream {
  public PDMetadata(global::DripSharp.PdfCarton.Pdmodel.PDDocument document) : base(document) {
    this.GetCOSObject().SetName(global::DripSharp.PdfCarton.Cos.COSName.Type, "Metadata");
    this.GetCOSObject().SetName(global::DripSharp.PdfCarton.Cos.COSName.Subtype, "XML");
  }

  public PDMetadata(global::DripSharp.PdfCarton.Pdmodel.PDDocument doc,
    global::System.IO.Stream str) : base(doc, str) {
    this.GetCOSObject().SetName(global::DripSharp.PdfCarton.Cos.COSName.Type, "Metadata");
    this.GetCOSObject().SetName(global::DripSharp.PdfCarton.Cos.COSName.Subtype, "XML");
  }

  public PDMetadata(global::DripSharp.PdfCarton.Cos.COSStream str) : base(str) {

  }

  public virtual global::System.IO.Stream ExportXMPMetadata() {
    return this.CreateInputStream();
  }

  public virtual void ImportXMPMetadata(sbyte[] xmp) { {
      global::System.IO.Stream os = this.CreateOutputStream();
      global::System.Exception __dripsharpPrimary_99_27_0 = null!;
      try {
        global::DripSharp.Runtime.JavaCompat.OutputStreamWrite(os, xmp);
      } catch (global::System.Exception __dripsharpCaught_99_27_0) {
        __dripsharpPrimary_99_27_0 = __dripsharpCaught_99_27_0;
        throw;
      } finally {
        global::DripSharp.Runtime.JavaCompat.CloseResource(os, __dripsharpPrimary_99_27_0);
      }
    }
  }

  static PDMetadata() {
    global::System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(typeof(global::DripSharp.PdfCarton.Pdmodel.Common.PDStream).TypeHandle);
  }
}
