// <auto-generated />
// Mechanically translated from: org/apache/fontbox/ttf/table/common/LookupTable.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Fonts.Ttf.Table.Common;

public class LookupTable {
  private readonly int lookupType = default;

  private readonly int lookupFlag = default;

  private readonly int markFilteringSet = default;

  private readonly global::DripSharp.PdfCarton.Fonts.Ttf.Table.Common.LookupSubTable[] subTables
    = null!;

  public LookupTable(int lookupType, int lookupFlag, int markFilteringSet,
    global::DripSharp.PdfCarton.Fonts.Ttf.Table.Common.LookupSubTable[] subTables) {
    this.lookupType = lookupType;
    this.lookupFlag = lookupFlag;
    this.markFilteringSet = markFilteringSet;
    this.subTables = subTables;
  }

  public virtual int GetLookupType() {
    return this.lookupType;
  }

  public virtual int GetLookupFlag() {
    return this.lookupFlag;
  }

  public virtual int GetMarkFilteringSet() {
    return this.markFilteringSet;
  }

  public virtual global::DripSharp.PdfCarton.Fonts.Ttf.Table.Common.LookupSubTable[] GetSubTables() {
    return this.subTables;
  }

  public override string ToString() {
    return global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.JavaStringFormat("LookupTable[lookupType=%d,lookupFlag=%d,markFilteringSet=%d]",
      this.lookupType, this.lookupFlag, this.markFilteringSet);
  }
}
