// <auto-generated />
// Mechanically translated from: org/apache/fontbox/ttf/table/common/ScriptTable.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Fonts.Ttf.Table.Common;

public class ScriptTable {
private readonly global::DripSharp.PdfCarton.Fonts.Ttf.Table.Common.LangSysTable defaultLangSysTable = null!;

private readonly global::System.Collections.Generic.IDictionary<string, global::DripSharp.PdfCarton.Fonts.Ttf.Table.Common.LangSysTable> langSysTables = null!;

public ScriptTable(global::DripSharp.PdfCarton.Fonts.Ttf.Table.Common.LangSysTable defaultLangSysTable, global::System.Collections.Generic.IDictionary<string, global::DripSharp.PdfCarton.Fonts.Ttf.Table.Common.LangSysTable> langSysTables) {
this.defaultLangSysTable = defaultLangSysTable;
this.langSysTables = langSysTables;
}

public virtual global::DripSharp.PdfCarton.Fonts.Ttf.Table.Common.LangSysTable GetDefaultLangSysTable() {
return this.defaultLangSysTable;
}

public virtual global::System.Collections.Generic.IDictionary<string, global::DripSharp.PdfCarton.Fonts.Ttf.Table.Common.LangSysTable> GetLangSysTables() {
return this.langSysTables;
}

public override string ToString() {
return global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.JavaStringFormat("ScriptTable[hasDefault=%s,langSysRecordsCount=%d]", (this.defaultLangSysTable != default!), global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.MapCount(this.langSysTables));
}
}
