// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/preflight/annotation/WidgetAnnotationValidator.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Preflight.Annotation;

public class WidgetAnnotationValidator
: global::DripSharp.PdfCarton.Preflight.Annotation.AnnotationValidator {
  protected internal global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.PDAnnotationWidget PdWidget
    = default!;

  public WidgetAnnotationValidator(global::DripSharp.PdfCarton.Preflight.PreflightContext ctx,
    global::DripSharp.PdfCarton.Cos.COSDictionary annotDictionary) : base(ctx, annotDictionary) {
    this.PdWidget
      = new global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.PDAnnotationWidget(annotDictionary);
    this.PdAnnot = this.PdWidget;
  }

  public override bool Validate() {
    bool isValid = base.Validate();
    return (this.CheckAAField() && isValid);
  }

  protected internal virtual bool CheckAAField() {
    if ((this.PdWidget.GetActions() != default!)) {
      base.Ctx.AddValidationError(new global::DripSharp.PdfCarton.Preflight.ValidationResult.ValidationError(global::DripSharp.PdfCarton.Preflight.PreflightConstants.ErrorAnnotForbiddenAa));
      return false;
    }
    return true;
  }
}
