// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/pdmodel/interactive/annotation/PDAnnotationTextMarkup.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Pdmodel.Interactive.Annotation;

public class PDAnnotationTextMarkup
: global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.PDAnnotationMarkup {
  protected internal PDAnnotationTextMarkup(string subType) {
    this.SetSubtype(subType);
    this.SetQuadPoints(new float[0]);
  }

  protected internal PDAnnotationTextMarkup(global::DripSharp.PdfCarton.Cos.COSDictionary field)
  : base(field) {

  }

  public void SetQuadPoints(float[] quadPoints) {
    global::DripSharp.PdfCarton.Cos.COSArray newQuadPoints
      = new global::DripSharp.PdfCarton.Cos.COSArray();
    newQuadPoints.SetFloatArray(quadPoints);
    this.GetCOSObject().SetItem(global::DripSharp.PdfCarton.Cos.COSName.Quadpoints, newQuadPoints);
  }

  public virtual float[] GetQuadPoints() {
    global::DripSharp.PdfCarton.Cos.COSArray array
      = this.GetCOSObject().GetCOSArray(global::DripSharp.PdfCarton.Cos.COSName.Quadpoints);
    return ((array != default!) ? array.ToFloatArray() : (float[])(default!));
  }
}
