// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/pdmodel/graphics/shading/PDMeshBasedShadingType.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Pdmodel.Graphics.Shading;

public abstract class PDMeshBasedShadingType : global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.PDShadingType4 {
private static readonly global::Microsoft.Extensions.Logging.ILogger LOG = global::Microsoft.Extensions.Logging.Abstractions.NullLogger.Instance;

internal PDMeshBasedShadingType(global::DripSharp.PdfCarton.Cos.COSDictionary shadingDictionary) : base(shadingDictionary) {

}

internal global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.Patch> collectPatches(global::SkiaSharp.SKMatrix xform, global::DripSharp.PdfCarton.Util.Matrix matrix, int controlPoints) {
global::DripSharp.PdfCarton.Cos.COSDictionary dict = this.GetCOSObject();
if (!((dict is global::DripSharp.PdfCarton.Cos.COSStream))) {
return global::System.Array.Empty<global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.Patch>();
}
global::DripSharp.PdfCarton.Pdmodel.Common.PDRange rangeX = this.GetDecodeForParameter(0);
global::DripSharp.PdfCarton.Pdmodel.Common.PDRange rangeY = this.GetDecodeForParameter(1);
if (((((rangeX == default!) || (rangeY == default!)) || (global::DripSharp.Runtime.JavaCompat.CompareFloat(rangeX.GetMin(), rangeX.GetMax()) == 0)) || (global::DripSharp.Runtime.JavaCompat.CompareFloat(rangeY.GetMin(), rangeY.GetMax()) == 0))) {
return global::System.Array.Empty<global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.Patch>();
}
int bitsPerFlag = this.GetBitsPerFlag();
global::DripSharp.PdfCarton.Pdmodel.Common.PDRange[] colRange = new global::DripSharp.PdfCarton.Pdmodel.Common.PDRange[this.GetNumberOfColorComponents()];
for (int i = 0; (i < colRange.Length); ++i) {
colRange[i] = this.GetDecodeForParameter((2 + i));
if ((colRange[i] == default!)) {
throw new global::System.IO.IOException("Range missing in shading /Decode entry");
}
}
global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.Patch> list = new global::System.Collections.Generic.List<global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.Patch>();
long maxSrcCoord = ((long)(global::System.Math.Pow((double)(2), (double)(this.GetBitsPerCoordinate()))) - 1);
long maxSrcColor = ((long)(global::System.Math.Pow((double)(2), (double)(this.GetBitsPerComponent()))) - 1);
using (global::System.IO.Stream imageStream = ((global::DripSharp.PdfCarton.Cos.COSStream)(dict!)).CreateInputStream()) {
using (global::DripSharp.Runtime.JavaImageInputStream mciis = new global::DripSharp.Runtime.JavaImageInputStream(imageStream)) {
global::DripSharp.Runtime.JavaPoint2D[] implicitEdge = new global::DripSharp.Runtime.JavaPoint2D[4];
float[][] implicitCornerColor = global::DripSharp.Runtime.JavaCompat.NewJaggedArray<float>(2, colRange.Length);
sbyte flag = unchecked((sbyte)(0));
try {
flag = unchecked((sbyte)((sbyte)((mciis.ReadBits(bitsPerFlag) & 3))));
} catch (global::System.IO.EndOfStreamException ex) {
global::Microsoft.Extensions.Logging.LoggerExtensions.LogError(global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.PDMeshBasedShadingType.LOG, global::DripSharp.Runtime.JavaCompat.StringValueOf(ex));
return list;
}
bool eof = false;
while (!eof) {
try {
bool isFree = ((int)(flag) == 0);
global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.Patch current = this.ReadPatch(mciis, isFree, implicitEdge, implicitCornerColor, maxSrcCoord, maxSrcColor, rangeX, rangeY, colRange, matrix, xform, controlPoints);
if ((current == default!)) {
break;
}
global::DripSharp.Runtime.JavaCompat.Add(list, current);
flag = unchecked((sbyte)((sbyte)((mciis.ReadBits(bitsPerFlag) & 3))));
switch (flag) {
case var __case_128_30_0 when __case_128_30_0 == unchecked((sbyte)(0)):
break;
case var __case_130_30_0 when __case_130_30_0 == unchecked((sbyte)(1)):
implicitEdge = current.GetFlag1Edge();
implicitCornerColor = current.GetFlag1Color();
break;
case var __case_134_30_0 when __case_134_30_0 == unchecked((sbyte)(2)):
implicitEdge = current.GetFlag2Edge();
implicitCornerColor = current.GetFlag2Color();
break;
case var __case_138_30_0 when __case_138_30_0 == unchecked((sbyte)(3)):
implicitEdge = current.GetFlag3Edge();
implicitCornerColor = current.GetFlag3Color();
break;
default:
global::Microsoft.Extensions.Logging.LoggerExtensions.LogWarning(global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.PDMeshBasedShadingType.LOG, global::DripSharp.Runtime.JavaCompat.StringValueOf(global::DripSharp.Runtime.JavaCompat.Concat("bad flag: ", flag)));
break;
}
} catch (global::System.IO.EndOfStreamException) {
eof = true;
}
}
}
}
return list;
}

protected internal virtual global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.Patch ReadPatch(global::DripSharp.Runtime.JavaImageInputStream input, bool isFree, global::DripSharp.Runtime.JavaPoint2D[] implicitEdge, float[][] implicitCornerColor, long maxSrcCoord, long maxSrcColor, global::DripSharp.PdfCarton.Pdmodel.Common.PDRange rangeX, global::DripSharp.PdfCarton.Pdmodel.Common.PDRange rangeY, global::DripSharp.PdfCarton.Pdmodel.Common.PDRange[] colRange, global::DripSharp.PdfCarton.Util.Matrix matrix, global::SkiaSharp.SKMatrix xform, int controlPoints) {
int numberOfColorComponents = this.GetNumberOfColorComponents();
float[][] color = global::DripSharp.Runtime.JavaCompat.NewJaggedArray<float>(4, numberOfColorComponents);
global::DripSharp.Runtime.JavaPoint2D[] points = new global::DripSharp.Runtime.JavaPoint2D[controlPoints];
int pStart = 4;
int cStart = 2;
if (isFree) {
pStart = 0;
cStart = 0;
} else {
points[0] = implicitEdge[0];
points[1] = implicitEdge[1];
points[2] = implicitEdge[2];
points[3] = implicitEdge[3];
for (int i__197_22 = 0; (i__197_22 < numberOfColorComponents); i__197_22++) {
color[0][i__197_22] = implicitCornerColor[0][i__197_22];
color[1][i__197_22] = implicitCornerColor[1][i__197_22];
}
}
try {
int bitsPerCoordinate = this.GetBitsPerCoordinate();
for (int i__207_22 = pStart; (i__207_22 < controlPoints); i__207_22++) {
long x = input.ReadBits(bitsPerCoordinate);
long y = input.ReadBits(bitsPerCoordinate);
float px = this.Interpolate((float)(x), maxSrcCoord, rangeX.GetMin(), rangeX.GetMax());
float py = this.Interpolate((float)(y), maxSrcCoord, rangeY.GetMin(), rangeY.GetMax());
global::DripSharp.Runtime.JavaPoint2D p = matrix.TransformPoint(px, py);
global::DripSharp.Runtime.PdfCartonFontCompat.TransformPoint(xform, p, p);
points[i__207_22] = p;
}
int bitsPerComponent = this.GetBitsPerComponent();
for (int i__218_22 = cStart; (i__218_22 < 4); i__218_22++) {
for (int j = 0; (j < numberOfColorComponents); j++) {
long c = input.ReadBits(bitsPerComponent);
color[i__218_22][j] = this.Interpolate((float)(c), maxSrcColor, colRange[j].GetMin(), colRange[j].GetMax());
}
}
} catch (global::System.IO.EndOfStreamException ex) {
global::Microsoft.Extensions.Logging.LoggerExtensions.LogDebug(global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.PDMeshBasedShadingType.LOG, (global::System.Exception)ex, global::DripSharp.Runtime.JavaCompat.StringValueOf("EOF"));
return default!;
}
return this.generatePatch(points, color);
}

protected internal abstract global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.Patch generatePatch(global::DripSharp.Runtime.JavaPoint2D[] points, float[][] color);

public abstract override global::SkiaSharp.SKRect GetBounds(global::SkiaSharp.SKMatrix xform, global::DripSharp.PdfCarton.Util.Matrix matrix);

internal virtual global::SkiaSharp.SKRect getBounds(global::SkiaSharp.SKMatrix xform, global::DripSharp.PdfCarton.Util.Matrix matrix, int controlPoints) {
global::SkiaSharp.SKRect bounds = default!;
foreach (global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.Patch patch in this.collectPatches(xform, matrix, controlPoints)) {
foreach (global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.ShadedTriangle shadedTriangle in patch.ListOfTriangles) {
if ((bounds! == default!)) {
bounds = global::DripSharp.Runtime.PdfCartonFontCompat.Rectangle(shadedTriangle.Corner[0].X, shadedTriangle.Corner[0].Y, (double)(0), (double)(0));
}
global::DripSharp.Runtime.PdfCartonFontCompat.AddPoint(ref bounds!, shadedTriangle.Corner[0]);
global::DripSharp.Runtime.PdfCartonFontCompat.AddPoint(ref bounds!, shadedTriangle.Corner[1]);
global::DripSharp.Runtime.PdfCartonFontCompat.AddPoint(ref bounds!, shadedTriangle.Corner[2]);
}
}
return bounds!;
}
}
