// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/pdmodel/graphics/shading/Type6ShadingContext.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Pdmodel.Graphics.Shading;

internal class Type6ShadingContext
: global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.PatchMeshesShadingContext {
  internal Type6ShadingContext(global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.PDShadingType6 shading,
    global::DripSharp.Runtime.JavaColorModel colorModel, global::SkiaSharp.SKMatrix xform,
    global::DripSharp.PdfCarton.Util.Matrix matrix, global::SkiaSharp.SKRectI deviceBounds)
  : base(shading, colorModel, xform, matrix, deviceBounds, 12) {

  }
}
