// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/pdmodel/graphics/color/PDCalRGB.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Pdmodel.Graphics.Color;

public class PDCalRGB
: global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDCIEDictionaryBasedColorSpace {
  private readonly global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDColor initialColor;

  public PDCalRGB() : base(global::DripSharp.PdfCarton.Cos.COSName.Calrgb) {
    this.initialColor
      = new global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDColor(new float[] { 0, 0, 0 },
      this);
  }

  public PDCalRGB(global::DripSharp.PdfCarton.Cos.COSArray rgb) : base(rgb) {
    this.initialColor
      = new global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDColor(new float[] { 0, 0, 0 },
      this);
  }

  public override string GetName() {
    return global::DripSharp.PdfCarton.Cos.COSName.Calrgb.GetName();
  }

  public override int GetNumberOfComponents() {
    return 3;
  }

  public override float[] GetDefaultDecode(int bitsPerComponent) {
    return new float[] { 0, 1, 0, 1, 0, 1 };
  }

  public override global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDColor GetInitialColor() {
    return this.initialColor;
  }

  public override float[] ToRGB(float[] value) {
    if (this.IsWhitePoint()) {
      float a = value[0];
      float b = value[1];
      float c = value[2];
      global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDGamma gamma = this.GetGamma();
      float powAR = (float)(global::System.Math.Pow((double)(a), (double)(gamma.GetR())));
      float powBG = (float)(global::System.Math.Pow((double)(b), (double)(gamma.GetG())));
      float powCB = (float)(global::System.Math.Pow((double)(c), (double)(gamma.GetB())));
      float[] matrix = this.GetMatrix();
      float mXA = matrix[0];
      float mYA = matrix[1];
      float mZA = matrix[2];
      float mXB = matrix[3];
      float mYB = matrix[4];
      float mZB = matrix[5];
      float mXC = matrix[6];
      float mYC = matrix[7];
      float mZC = matrix[8];
      float x = (((mXA * powAR) + (mXB * powBG)) + (mXC * powCB));
      float y = (((mYA * powAR) + (mYB * powBG)) + (mYC * powCB));
      float z = (((mZA * powAR) + (mZB * powBG)) + (mZC * powCB));
      return this.ConvXYZtoRGB(x, y, z);
    } else {
      return new float[] { value[0], value[1], value[2] };
    }
  }

  public global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDGamma GetGamma() {
    global::DripSharp.PdfCarton.Cos.COSArray gammaArray
      = base.Dictionary.GetCOSArray(global::DripSharp.PdfCarton.Cos.COSName.Gamma);
    if ((gammaArray == default!)) {
      gammaArray = new global::DripSharp.PdfCarton.Cos.COSArray();
      gammaArray.Add(global::DripSharp.PdfCarton.Cos.COSFloat.One);
      gammaArray.Add(global::DripSharp.PdfCarton.Cos.COSFloat.One);
      gammaArray.Add(global::DripSharp.PdfCarton.Cos.COSFloat.One);
      base.Dictionary.SetItem(global::DripSharp.PdfCarton.Cos.COSName.Gamma, gammaArray);
    }
    return new global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDGamma(gammaArray);
  }

  public float[] GetMatrix() {
    global::DripSharp.PdfCarton.Cos.COSArray matrix
      = base.Dictionary.GetCOSArray(global::DripSharp.PdfCarton.Cos.COSName.Matrix);
    if ((matrix == default!)) {
      return new float[] { 1, 0, 0, 0, 1, 0, 0, 0, 1 };
    } else {
      return matrix.ToFloatArray();
    }
  }

  public void SetGamma(global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDGamma gamma) {
    global::DripSharp.PdfCarton.Cos.COSArray gammaArray = default!;
    if ((gamma != default!)) {
      gammaArray = gamma.GetCOSArray();
    }
    base.Dictionary.SetItem(global::DripSharp.PdfCarton.Cos.COSName.Gamma, gammaArray!);
  }

  public void SetMatrix(global::DripSharp.PdfCarton.Util.Matrix matrix) {
    global::DripSharp.PdfCarton.Cos.COSArray matrixArray = default!;
    if ((matrix != default!)) {
      float[][] values = matrix.GetValues();
      matrixArray = new global::DripSharp.PdfCarton.Cos.COSArray();
      matrixArray!.Add(new global::DripSharp.PdfCarton.Cos.COSFloat(values[0][0]));
      matrixArray!.Add(new global::DripSharp.PdfCarton.Cos.COSFloat(values[0][1]));
      matrixArray!.Add(new global::DripSharp.PdfCarton.Cos.COSFloat(values[0][2]));
      matrixArray!.Add(new global::DripSharp.PdfCarton.Cos.COSFloat(values[1][0]));
      matrixArray!.Add(new global::DripSharp.PdfCarton.Cos.COSFloat(values[1][1]));
      matrixArray!.Add(new global::DripSharp.PdfCarton.Cos.COSFloat(values[1][2]));
      matrixArray!.Add(new global::DripSharp.PdfCarton.Cos.COSFloat(values[2][0]));
      matrixArray!.Add(new global::DripSharp.PdfCarton.Cos.COSFloat(values[2][1]));
      matrixArray!.Add(new global::DripSharp.PdfCarton.Cos.COSFloat(values[2][2]));
    }
    base.Dictionary.SetItem(global::DripSharp.PdfCarton.Cos.COSName.Matrix, matrixArray!);
  }
}
