// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/pdmodel/graphics/color/PDDeviceNAttributes.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Pdmodel.Graphics.Color;

public sealed class PDDeviceNAttributes {
  private static readonly global::Microsoft.Extensions.Logging.ILogger LOG
    = global::Microsoft.Extensions.Logging.Abstractions.NullLogger.Instance;

  private readonly global::DripSharp.PdfCarton.Cos.COSDictionary dictionary = null!;

  public PDDeviceNAttributes() {
    this.dictionary = new global::DripSharp.PdfCarton.Cos.COSDictionary();
  }

  public PDDeviceNAttributes(global::DripSharp.PdfCarton.Cos.COSDictionary attributes) {
    this.dictionary = attributes;
  }

  public global::DripSharp.PdfCarton.Cos.COSDictionary GetCOSDictionary() {
    return this.dictionary;
  }

  public global::System.Collections.Generic.IDictionary<string,
    global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDSeparation> GetColorants(global::DripSharp.PdfCarton.Pdmodel.PDResources resources) {
    global::System.Collections.Generic.IDictionary<string,
      global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDSeparation> actuals
      = global::DripSharp.Runtime.JavaCompat.NewJavaDictionary<string,
      global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDSeparation>();
    global::DripSharp.PdfCarton.Cos.COSDictionary colorants
      = this.dictionary.GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName.Colorants);
    if ((colorants == default!)) {
      colorants = new global::DripSharp.PdfCarton.Cos.COSDictionary();
      this.dictionary.SetItem(global::DripSharp.PdfCarton.Cos.COSName.Colorants, colorants);
    } else {
      foreach (global::DripSharp.PdfCarton.Cos.COSName name in colorants.KeySet()) {
        global::DripSharp.PdfCarton.Cos.COSBase value = colorants.GetDictionaryObject(name);
        global::DripSharp.Runtime.JavaCompat.MapPut(actuals, name.GetName(),
          (global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDSeparation)(global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDColorSpace.Create(value,
          resources)!));
      }
    }
    return new global::DripSharp.PdfCarton.Pdmodel.Common.COSDictionaryMap<string,
      global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDSeparation>(actuals, colorants);
  }

  public global::System.Collections.Generic.IDictionary<string,
    global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDSeparation> GetColorants() {
    return this.GetColorants((global::DripSharp.PdfCarton.Pdmodel.PDResources)default!);
  }

  public global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDDeviceNProcess GetProcess() {
    global::DripSharp.PdfCarton.Cos.COSDictionary process
      = this.dictionary.GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName.Process);
    if ((process == default!)) {
      return default!;
    }
    return new global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDDeviceNProcess(process);
  }

  public bool IsNChannel() {
    return global::DripSharp.Runtime.JavaCompat.Equals("NChannel",
      this.dictionary.GetNameAsString(global::DripSharp.PdfCarton.Cos.COSName.Subtype));
  }

  public void SetColorants(global::System.Collections.Generic.IDictionary<string,
    global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDColorSpace> colorants) {
    global::DripSharp.PdfCarton.Cos.COSDictionary colorantDict = default!;
    if ((colorants != default!)) {
      colorantDict = global::DripSharp.PdfCarton.Pdmodel.Common.COSDictionaryMap<object,
        object>.Convert(global::DripSharp.Runtime.JavaCompat.CastDictionary<string,
        object>(colorants));
    }
    this.dictionary.SetItem(global::DripSharp.PdfCarton.Cos.COSName.Colorants, colorantDict!);
  }

  public override string ToString() {
    global::System.Text.StringBuilder sb
      = new global::System.Text.StringBuilder(this.dictionary.GetNameAsString(global::DripSharp.PdfCarton.Cos.COSName.Subtype));
    sb.Append('{');
    global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDDeviceNProcess process = this.GetProcess();
    if ((process != default!)) {
      sb.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(process));
      sb.Append(' ');
    }
    global::System.Collections.Generic.IDictionary<string,
      global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDSeparation> colorants;
    try {
      colorants = this.GetColorants((global::DripSharp.PdfCarton.Pdmodel.PDResources)default!);
      sb.Append("Colorants{");
      foreach (global::DripSharp.Runtime.JavaMapEntry<string,
        global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDSeparation> col in global::DripSharp.Runtime.JavaCompat.MapEntrySet(colorants)) {
        sb.Append('"');
        sb.Append(col.Key);
        sb.Append("\": ");
        sb.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(col.Value));
        sb.Append(' ');
      }
      sb.Append('}');
    } catch (global::System.IO.IOException e) {
      global::Microsoft.Extensions.Logging.LoggerExtensions.LogDebug(global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDDeviceNAttributes.LOG,
        (global::System.Exception)e,
        global::DripSharp.Runtime.JavaCompat.StringValueOf("Couldn't get the colorants information - returning 'ERROR' instead'"));
      sb.Append("ERROR");
    }
    sb.Append('}');
    return sb.ToString();
  }
}
