// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/pdmodel/interactive/annotation/handlers/PDPolylineAppearanceHandler.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.Handlers;

public class PDPolylineAppearanceHandler : global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.Handlers.PDAbstractAppearanceHandler {
private static readonly global::Microsoft.Extensions.Logging.ILogger LOG = global::Microsoft.Extensions.Logging.Abstractions.NullLogger.Instance;

public PDPolylineAppearanceHandler(global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.PDAnnotation annotation) : base(annotation) {

}

public PDPolylineAppearanceHandler(global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.PDAnnotation annotation, global::DripSharp.PdfCarton.Pdmodel.PDDocument document) : base(annotation, document) {

}

public override void GenerateNormalAppearance() {
global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.PDAnnotationPolyline annotation = (global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.PDAnnotationPolyline)(this.getAnnotation()!);
global::DripSharp.PdfCarton.Pdmodel.Common.PDRectangle rect = annotation.GetRectangle();
if ((rect == default!)) {
return;
}
float[] pathsArray = annotation.GetVertices();
if (((pathsArray == default!) || (pathsArray.Length < 4))) {
return;
}
global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.Handlers.AnnotationBorder ab = global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.Handlers.AnnotationBorder.getAnnotationBorder(annotation, annotation.GetBorderStyle());
global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDColor color = annotation.GetColor();
if ((((color == default!) || (color.GetComponents().Length == 0)) || (global::DripSharp.Runtime.JavaCompat.CompareFloat(ab.width, (float)(0)) == 0))) {
return;
}
float minX = float.MaxValue;
float minY = float.MaxValue;
float maxX = float.Epsilon;
float maxY = float.Epsilon;
for (int i__78_18 = 0; (i__78_18 < (pathsArray.Length / 2)); ++i__78_18) {
float x__80_19 = pathsArray[(i__78_18 * 2)];
float y__81_19 = pathsArray[((i__78_18 * 2) + 1)];
minX = global::System.Math.Min(minX, x__80_19);
minY = global::System.Math.Min(minY, y__81_19);
maxX = global::System.Math.Max(maxX, x__80_19);
maxY = global::System.Math.Max(maxY, y__81_19);
}
rect.SetLowerLeftX(global::System.Math.Min((minX - (ab.width * 10)), rect.GetLowerLeftX()));
rect.SetLowerLeftY(global::System.Math.Min((minY - (ab.width * 10)), rect.GetLowerLeftY()));
rect.SetUpperRightX(global::System.Math.Max((maxX + (ab.width * 10)), rect.GetUpperRightX()));
rect.SetUpperRightY(global::System.Math.Max((maxY + (ab.width * 10)), rect.GetUpperRightY()));
annotation.SetRectangle(rect);
try {
using (global::DripSharp.PdfCarton.Pdmodel.PDAppearanceContentStream cs = this.getNormalAppearanceAsContentStream()) {
bool hasBackground = cs.SetNonStrokingColorOnDemand(annotation.GetInteriorColor());
this.setOpacity(cs, annotation.GetConstantOpacity());
bool hasStroke = cs.SetStrokingColorOnDemand(color);
if ((ab.dashArray != default!)) {
cs.SetLineDashPattern(ab.dashArray, (float)(0));
}
cs.SetLineWidth(ab.width);
string startPointEndingStyle = annotation.GetStartPointEndingStyle();
string endPointEndingStyle = annotation.GetEndPointEndingStyle();
for (int i__108_22 = 0; (i__108_22 < (pathsArray.Length / 2)); ++i__108_22) {
float x__110_23 = pathsArray[(i__108_22 * 2)];
float y__111_23 = pathsArray[((i__108_22 * 2) + 1)];
if ((i__108_22 == 0)) {
if (global::DripSharp.Runtime.JavaCompat.CollectionContains(global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.Handlers.PDAbstractAppearanceHandler.ShortStyles, startPointEndingStyle)) {
float x1__118_31 = pathsArray[2];
float y1__119_31 = pathsArray[3];
float len__120_31 = (float)(global::System.Math.Sqrt((global::System.Math.Pow((double)((x__110_23 - x1__118_31)), (double)(2)) + global::System.Math.Pow((double)((y__111_23 - y1__119_31)), (double)(2)))));
if ((global::DripSharp.Runtime.JavaCompat.CompareFloat(len__120_31, (float)(0)) != 0)) {
x__110_23 += (((float)((x1__118_31 - x__110_23)) / (float)(len__120_31)) * ab.width);
y__111_23 += (((float)((y1__119_31 - y__111_23)) / (float)(len__120_31)) * ab.width);
}
}
cs.MoveTo(x__110_23, y__111_23);
} else {
if (((i__108_22 == ((pathsArray.Length / 2) - 1)) && global::DripSharp.Runtime.JavaCompat.CollectionContains(global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.Handlers.PDAbstractAppearanceHandler.ShortStyles, endPointEndingStyle))) {
float x0 = pathsArray[(pathsArray.Length - 4)];
float y0 = pathsArray[(pathsArray.Length - 3)];
float len__137_31 = (float)(global::System.Math.Sqrt((global::System.Math.Pow((double)((x0 - x__110_23)), (double)(2)) + global::System.Math.Pow((double)((y0 - y__111_23)), (double)(2)))));
if ((global::DripSharp.Runtime.JavaCompat.CompareFloat(len__137_31, (float)(0)) != 0)) {
x__110_23 -= (((float)((x__110_23 - x0)) / (float)(len__137_31)) * ab.width);
y__111_23 -= (((float)((y__111_23 - y0)) / (float)(len__137_31)) * ab.width);
}
}
cs.LineTo(x__110_23, y__111_23);
}
}
cs.Stroke();
if (!(global::DripSharp.Runtime.JavaCompat.Equals(global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.PDAnnotationLine.LeNone, startPointEndingStyle))) {
float x2__157_23 = pathsArray[2];
float y2__158_23 = pathsArray[3];
float x1__159_23 = pathsArray[0];
float y1__160_23 = pathsArray[1];
cs.SaveGraphicsState();
if (global::DripSharp.Runtime.JavaCompat.CollectionContains(global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.Handlers.PDAbstractAppearanceHandler.AngledStyles, startPointEndingStyle)) {
double angle__164_28 = global::System.Math.Atan2((double)((y2__158_23 - y1__160_23)), (double)((x2__157_23 - x1__159_23)));
cs.Transform(global::DripSharp.PdfCarton.Util.Matrix.GetRotateInstance(angle__164_28, x1__159_23, y1__160_23));
} else {
cs.Transform(global::DripSharp.PdfCarton.Util.Matrix.GetTranslateInstance(x1__159_23, y1__160_23));
}
this.drawStyle(startPointEndingStyle, cs, (float)(0), (float)(0), ab.width, hasStroke, hasBackground, false);
cs.RestoreGraphicsState();
}
if (!(global::DripSharp.Runtime.JavaCompat.Equals(global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.PDAnnotationLine.LeNone, endPointEndingStyle))) {
float x1__178_23 = pathsArray[(pathsArray.Length - 4)];
float y1__179_23 = pathsArray[(pathsArray.Length - 3)];
float x2__180_23 = pathsArray[(pathsArray.Length - 2)];
float y2__181_23 = pathsArray[(pathsArray.Length - 1)];
if (global::DripSharp.Runtime.JavaCompat.CollectionContains(global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.Handlers.PDAbstractAppearanceHandler.AngledStyles, endPointEndingStyle)) {
double angle__185_28 = global::System.Math.Atan2((double)((y2__181_23 - y1__179_23)), (double)((x2__180_23 - x1__178_23)));
cs.Transform(global::DripSharp.PdfCarton.Util.Matrix.GetRotateInstance(angle__185_28, x2__180_23, y2__181_23));
} else {
cs.Transform(global::DripSharp.PdfCarton.Util.Matrix.GetTranslateInstance(x2__180_23, y2__181_23));
}
this.drawStyle(endPointEndingStyle, cs, (float)(0), (float)(0), ab.width, hasStroke, hasBackground, true);
}
}
} catch (global::System.IO.IOException ex) {
global::Microsoft.Extensions.Logging.LoggerExtensions.LogError(global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.Handlers.PDPolylineAppearanceHandler.LOG, global::DripSharp.Runtime.JavaCompat.StringValueOf(ex));
}
}

public override void GenerateRolloverAppearance() {}

public override void GenerateDownAppearance() {}
}
