// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/cos/COSBase.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Cos;

public abstract class COSBase : global::DripSharp.PdfCarton.Pdmodel.Common.COSObjectable {
private bool direct = default;

private global::DripSharp.PdfCarton.Cos.COSObjectKey key = null!;

public COSBase() {}

public virtual global::DripSharp.PdfCarton.Cos.COSBase GetCOSObject() {
return this;
}

public abstract void Accept(global::DripSharp.PdfCarton.Cos.ICOSVisitor visitor);

public virtual bool IsDirect() {
return this.direct;
}

public virtual void SetDirect(bool direct) {
this.direct = direct;
}

public virtual global::DripSharp.PdfCarton.Cos.COSObjectKey GetKey() {
return this.key;
}

public virtual void SetKey(global::DripSharp.PdfCarton.Cos.COSObjectKey key) {
this.key = key;
}
}
