// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/cos/COSDictionary.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Cos;

public class COSDictionary : global::DripSharp.PdfCarton.Cos.COSBase, global::DripSharp.PdfCarton.Cos.COSUpdateInfo {
private static readonly global::Microsoft.Extensions.Logging.ILogger LOG = global::Microsoft.Extensions.Logging.Abstractions.NullLogger.Instance;

private const string PATH_SEPARATOR = "/";

protected internal global::System.Collections.Generic.IDictionary<global::DripSharp.PdfCarton.Cos.COSName, global::DripSharp.PdfCarton.Cos.COSBase> Items = new global::DripSharp.Runtime.JavaLinkedHashMap<global::DripSharp.PdfCarton.Cos.COSName, global::DripSharp.PdfCarton.Cos.COSBase>();

private readonly global::DripSharp.PdfCarton.Cos.COSUpdateState updateState = null!;

public COSDictionary() {
this.updateState = new global::DripSharp.PdfCarton.Cos.COSUpdateState(this);
}

public COSDictionary(global::DripSharp.PdfCarton.Cos.COSDictionary dict) {
this.updateState = new global::DripSharp.PdfCarton.Cos.COSUpdateState(this);
this.AddAll(dict);
}

public virtual bool ContainsValue(object value) {
bool contains = global::DripSharp.Runtime.JavaCompat.MapContainsValue(this.Items, value);
if ((!contains && (value is global::DripSharp.PdfCarton.Cos.COSObject))) {
contains = global::DripSharp.Runtime.JavaCompat.MapContainsValue(this.Items, ((global::DripSharp.PdfCarton.Cos.COSObject)(value!)).GetObject());
}
return contains;
}

public virtual global::DripSharp.PdfCarton.Cos.COSName GetKeyForValue(object value) {
foreach (global::DripSharp.Runtime.JavaMapEntry<global::DripSharp.PdfCarton.Cos.COSName, global::DripSharp.PdfCarton.Cos.COSBase> entry in global::DripSharp.Runtime.JavaCompat.MapEntrySet(this.Items)) {
object nextValue = entry.Value;
if ((global::DripSharp.Runtime.JavaCompat.Equals(nextValue, value) || (((nextValue is global::DripSharp.PdfCarton.Cos.COSObject) && !(((global::DripSharp.PdfCarton.Cos.COSObject)(nextValue!)).IsObjectNull())) && global::DripSharp.Runtime.JavaCompat.Equals(((global::DripSharp.PdfCarton.Cos.COSObject)(nextValue!)).GetObject(), value)))) {
return entry.Key;
}
}
return default!;
}

public virtual int Size() {
return global::DripSharp.Runtime.JavaCompat.MapCount(this.Items);
}

public virtual void Clear() {
this.Items.Clear();
this.GetUpdateState().update();
}

public virtual global::DripSharp.PdfCarton.Cos.COSBase GetDictionaryObject(string key) {
return this.GetDictionaryObject(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key));
}

public virtual global::DripSharp.PdfCarton.Cos.COSBase GetDictionaryObject(global::DripSharp.PdfCarton.Cos.COSName firstKey, global::DripSharp.PdfCarton.Cos.COSName secondKey) {
global::DripSharp.PdfCarton.Cos.COSBase retval = this.GetDictionaryObject(firstKey);
if (((retval == default!) && (secondKey != default!))) {
retval = this.GetDictionaryObject(secondKey);
}
return retval;
}

public virtual global::DripSharp.PdfCarton.Cos.COSBase GetDictionaryObject(global::DripSharp.PdfCarton.Cos.COSName key) {
global::DripSharp.PdfCarton.Cos.COSBase retval = global::DripSharp.Runtime.JavaCompat.MapGet(this.Items, key);
if ((retval is global::DripSharp.PdfCarton.Cos.COSObject)) {
retval = ((global::DripSharp.PdfCarton.Cos.COSObject)(retval!)).GetObject();
}
if ((retval is global::DripSharp.PdfCarton.Cos.COSNull)) {
retval = default!;
}
return retval;
}

public virtual void SetItem(global::DripSharp.PdfCarton.Cos.COSName key, global::DripSharp.PdfCarton.Cos.COSBase value) {
if ((value == default!)) {
this.RemoveItem(key);
} else {
if (((((value is global::DripSharp.PdfCarton.Cos.COSDictionary) || (value is global::DripSharp.PdfCarton.Cos.COSArray)) && !(value.IsDirect())) && (value.GetKey() != default!))) {
global::DripSharp.PdfCarton.Cos.COSObject cosObject = new global::DripSharp.PdfCarton.Cos.COSObject(value, value.GetKey());
global::DripSharp.Runtime.JavaCompat.MapPut(this.Items, key, cosObject);
this.GetUpdateState().update(cosObject);
} else {
global::DripSharp.Runtime.JavaCompat.MapPut(this.Items, key, value);
this.GetUpdateState().update(value);
}
}
}

public virtual void SetItem(global::DripSharp.PdfCarton.Cos.COSName key, global::DripSharp.PdfCarton.Pdmodel.Common.COSObjectable value) {
global::DripSharp.PdfCarton.Cos.COSBase @base = default!;
if ((value != default!)) {
@base = value.GetCOSObject();
}
this.SetItem(key, @base!);
}

public virtual void SetItem(string key, global::DripSharp.PdfCarton.Pdmodel.Common.COSObjectable value) {
this.SetItem(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), value);
}

public virtual void SetBoolean(string key, bool value) {
this.SetItem(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), global::DripSharp.PdfCarton.Cos.COSBoolean.GetBoolean(value));
}

public virtual void SetBoolean(global::DripSharp.PdfCarton.Cos.COSName key, bool value) {
this.SetItem(key, global::DripSharp.PdfCarton.Cos.COSBoolean.GetBoolean(value));
}

public virtual void SetItem(string key, global::DripSharp.PdfCarton.Cos.COSBase value) {
this.SetItem(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), value);
}

public virtual void SetName(string key, string value) {
this.SetName(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), value);
}

public virtual void SetName(global::DripSharp.PdfCarton.Cos.COSName key, string value) {
global::DripSharp.PdfCarton.Cos.COSName name = default!;
if ((value != default!)) {
name = global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(value);
}
this.SetItem(key, name!);
}

public virtual void SetDate(string key, global::System.DateTimeOffset? date) {
this.SetDate(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), date);
}

public virtual void SetDate(global::DripSharp.PdfCarton.Cos.COSName key, global::System.DateTimeOffset? date) {
this.SetString(key, global::DripSharp.PdfCarton.Util.DateConverter.ToString(date));
}

public virtual void SetEmbeddedDate(global::DripSharp.PdfCarton.Cos.COSName embedded, global::DripSharp.PdfCarton.Cos.COSName key, global::System.DateTimeOffset? date) {
global::DripSharp.PdfCarton.Cos.COSDictionary dic = this.GetCOSDictionary(embedded);
if (((dic == default!) && (date != default!))) {
dic = new global::DripSharp.PdfCarton.Cos.COSDictionary();
this.SetItem(embedded, dic);
}
if ((dic != default!)) {
dic.SetDate(key, date);
}
}

public virtual void SetString(string key, string value) {
this.SetString(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), value);
}

public virtual void SetString(global::DripSharp.PdfCarton.Cos.COSName key, string value) {
global::DripSharp.PdfCarton.Cos.COSString name = default!;
if ((value != default!)) {
name = new global::DripSharp.PdfCarton.Cos.COSString(value);
}
this.SetItem(key, name!);
}

public virtual void SetEmbeddedString(global::DripSharp.PdfCarton.Cos.COSName embedded, global::DripSharp.PdfCarton.Cos.COSName key, string value) {
global::DripSharp.PdfCarton.Cos.COSDictionary dic = this.GetCOSDictionary(embedded);
if (((dic == default!) && (value != default!))) {
dic = new global::DripSharp.PdfCarton.Cos.COSDictionary();
this.SetItem(embedded, dic);
}
if ((dic != default!)) {
dic.SetString(key, value);
}
}

public virtual void SetInt(string key, int value) {
this.SetInt(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), value);
}

public virtual void SetInt(global::DripSharp.PdfCarton.Cos.COSName key, int value) {
this.SetItem(key, global::DripSharp.PdfCarton.Cos.COSInteger.Get((long)(value)));
}

public virtual void SetLong(string key, long value) {
this.SetLong(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), value);
}

public virtual void SetLong(global::DripSharp.PdfCarton.Cos.COSName key, long value) {
global::DripSharp.PdfCarton.Cos.COSInteger intVal = global::DripSharp.PdfCarton.Cos.COSInteger.Get(value);
this.SetItem(key, intVal);
}

public virtual void SetEmbeddedInt(global::DripSharp.PdfCarton.Cos.COSName embeddedDictionary, global::DripSharp.PdfCarton.Cos.COSName key, int value) {
global::DripSharp.PdfCarton.Cos.COSDictionary embedded = this.GetCOSDictionary(embeddedDictionary);
if ((embedded == default!)) {
embedded = new global::DripSharp.PdfCarton.Cos.COSDictionary();
this.SetItem(embeddedDictionary, embedded);
}
embedded.SetInt(key, value);
}

public virtual void SetFloat(string key, float value) {
this.SetFloat(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), value);
}

public virtual void SetFloat(global::DripSharp.PdfCarton.Cos.COSName key, float value) {
global::DripSharp.PdfCarton.Cos.COSFloat fltVal = new global::DripSharp.PdfCarton.Cos.COSFloat(value);
this.SetItem(key, fltVal);
}

public virtual void SetFlag(global::DripSharp.PdfCarton.Cos.COSName field, int bitFlag, bool value) {
int currentFlags = this.GetInt(field, 0);
if (value) {
currentFlags = (currentFlags | bitFlag);
} else {
currentFlags &= ~bitFlag;
}
this.SetInt(field, currentFlags);
}

public virtual global::DripSharp.PdfCarton.Cos.COSName GetCOSName(global::DripSharp.PdfCarton.Cos.COSName key) {
global::DripSharp.PdfCarton.Cos.COSBase name = this.GetDictionaryObject(key);
if ((name is global::DripSharp.PdfCarton.Cos.COSName)) {
return (global::DripSharp.PdfCarton.Cos.COSName)(name!);
}
return default!;
}

public virtual global::DripSharp.PdfCarton.Cos.COSObject GetCOSObject(global::DripSharp.PdfCarton.Cos.COSName key) {
global::DripSharp.PdfCarton.Cos.COSBase @object = this.GetItem(key);
if ((@object is global::DripSharp.PdfCarton.Cos.COSObject)) {
return (global::DripSharp.PdfCarton.Cos.COSObject)(@object!);
}
return default!;
}

public virtual global::DripSharp.PdfCarton.Cos.COSDictionary GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName key) {
global::DripSharp.PdfCarton.Cos.COSBase dictionary = this.GetDictionaryObject(key);
if ((dictionary is global::DripSharp.PdfCarton.Cos.COSDictionary)) {
return (global::DripSharp.PdfCarton.Cos.COSDictionary)(dictionary!);
}
return default!;
}

public virtual global::DripSharp.PdfCarton.Cos.COSDictionary GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName firstKey, global::DripSharp.PdfCarton.Cos.COSName secondKey) {
global::DripSharp.PdfCarton.Cos.COSBase dictionary = this.GetDictionaryObject(firstKey, secondKey);
if ((dictionary is global::DripSharp.PdfCarton.Cos.COSDictionary)) {
return (global::DripSharp.PdfCarton.Cos.COSDictionary)(dictionary!);
}
return default!;
}

public virtual global::DripSharp.PdfCarton.Cos.COSStream GetCOSStream(global::DripSharp.PdfCarton.Cos.COSName key) {
global::DripSharp.PdfCarton.Cos.COSBase @base = this.GetDictionaryObject(key);
if ((@base is global::DripSharp.PdfCarton.Cos.COSStream)) {
return (global::DripSharp.PdfCarton.Cos.COSStream)(@base!);
}
return default!;
}

public virtual global::DripSharp.PdfCarton.Cos.COSArray GetCOSArray(global::DripSharp.PdfCarton.Cos.COSName key) {
global::DripSharp.PdfCarton.Cos.COSBase array = this.GetDictionaryObject(key);
if ((array is global::DripSharp.PdfCarton.Cos.COSArray)) {
return (global::DripSharp.PdfCarton.Cos.COSArray)(array!);
}
return default!;
}

public virtual global::DripSharp.PdfCarton.Cos.COSName GetCOSName(global::DripSharp.PdfCarton.Cos.COSName key, global::DripSharp.PdfCarton.Cos.COSName defaultValue) {
global::DripSharp.PdfCarton.Cos.COSBase name = this.GetDictionaryObject(key);
if ((name is global::DripSharp.PdfCarton.Cos.COSName)) {
return (global::DripSharp.PdfCarton.Cos.COSName)(name!);
}
return defaultValue;
}

public virtual string GetNameAsString(string key) {
return this.GetNameAsString(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key));
}

public virtual string GetNameAsString(global::DripSharp.PdfCarton.Cos.COSName key) {
string retval = default!;
global::DripSharp.PdfCarton.Cos.COSBase name = this.GetDictionaryObject(key);
if ((name is global::DripSharp.PdfCarton.Cos.COSName)) {
retval = ((global::DripSharp.PdfCarton.Cos.COSName)(name!)).GetName();
} else {
if ((name is global::DripSharp.PdfCarton.Cos.COSString)) {
retval = ((global::DripSharp.PdfCarton.Cos.COSString)(name!)).GetString();
}
}
return retval!;
}

public virtual string GetNameAsString(string key, string defaultValue) {
return this.GetNameAsString(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), defaultValue);
}

public virtual string GetNameAsString(global::DripSharp.PdfCarton.Cos.COSName key, string defaultValue) {
string retval = this.GetNameAsString(key);
if ((retval == default!)) {
retval = defaultValue;
}
return retval;
}

public virtual string GetString(string key) {
return this.GetString(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key));
}

public virtual string GetString(global::DripSharp.PdfCarton.Cos.COSName key) {
string retval = default!;
global::DripSharp.PdfCarton.Cos.COSBase value = this.GetDictionaryObject(key);
if ((value is global::DripSharp.PdfCarton.Cos.COSString)) {
retval = ((global::DripSharp.PdfCarton.Cos.COSString)(value!)).GetString();
}
return retval!;
}

public virtual string GetString(string key, string defaultValue) {
return this.GetString(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), defaultValue);
}

public virtual string GetString(global::DripSharp.PdfCarton.Cos.COSName key, string defaultValue) {
string retval = this.GetString(key);
if ((retval == default!)) {
retval = defaultValue;
}
return retval;
}

public virtual string GetEmbeddedString(global::DripSharp.PdfCarton.Cos.COSName embedded, global::DripSharp.PdfCarton.Cos.COSName key) {
return this.GetEmbeddedString(embedded, key, (string)default!);
}

public virtual string GetEmbeddedString(global::DripSharp.PdfCarton.Cos.COSName embedded, global::DripSharp.PdfCarton.Cos.COSName key, string defaultValue) {
global::DripSharp.PdfCarton.Cos.COSDictionary eDic = this.GetCOSDictionary(embedded);
return ((eDic != default!) ? eDic.GetString(key, defaultValue) : defaultValue);
}

public virtual global::System.DateTimeOffset? GetDate(string key) {
return this.GetDate(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key));
}

public virtual global::System.DateTimeOffset? GetDate(global::DripSharp.PdfCarton.Cos.COSName key) {
global::DripSharp.PdfCarton.Cos.COSBase @base = this.GetDictionaryObject(key);
if ((@base is global::DripSharp.PdfCarton.Cos.COSString)) {
return global::DripSharp.PdfCarton.Util.DateConverter.ToCalendar((global::DripSharp.PdfCarton.Cos.COSString)(@base!));
}
return default!;
}

public virtual global::System.DateTimeOffset? GetDate(string key, global::System.DateTimeOffset? defaultValue) {
return this.GetDate(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), defaultValue);
}

public virtual global::System.DateTimeOffset? GetDate(global::DripSharp.PdfCarton.Cos.COSName key, global::System.DateTimeOffset? defaultValue) {
global::System.DateTimeOffset? retval = this.GetDate(key);
if ((retval == default!)) {
retval = defaultValue;
}
return retval;
}

public virtual global::System.DateTimeOffset? GetEmbeddedDate(global::DripSharp.PdfCarton.Cos.COSName embedded, global::DripSharp.PdfCarton.Cos.COSName key) {
return this.GetEmbeddedDate(embedded, key, (global::System.DateTimeOffset?)default!);
}

public virtual global::System.DateTimeOffset? GetEmbeddedDate(global::DripSharp.PdfCarton.Cos.COSName embedded, global::DripSharp.PdfCarton.Cos.COSName key, global::System.DateTimeOffset? defaultValue) {
global::DripSharp.PdfCarton.Cos.COSDictionary eDic = this.GetCOSDictionary(embedded);
return ((eDic != default!) ? eDic.GetDate(key, defaultValue) : defaultValue);
}

public virtual bool GetBoolean(string key, bool defaultValue) {
return this.GetBoolean(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), defaultValue);
}

public virtual bool GetBoolean(global::DripSharp.PdfCarton.Cos.COSName key, bool defaultValue) {
return this.GetBoolean(key, (global::DripSharp.PdfCarton.Cos.COSName)default!, defaultValue);
}

public virtual bool GetBoolean(global::DripSharp.PdfCarton.Cos.COSName firstKey, global::DripSharp.PdfCarton.Cos.COSName secondKey, bool defaultValue) {
bool retval = defaultValue;
global::DripSharp.PdfCarton.Cos.COSBase @bool = this.GetDictionaryObject(firstKey, secondKey);
if ((@bool is global::DripSharp.PdfCarton.Cos.COSBoolean)) {
retval = (@bool == global::DripSharp.PdfCarton.Cos.COSBoolean.True);
}
return retval;
}

public virtual int GetEmbeddedInt(global::DripSharp.PdfCarton.Cos.COSName embeddedDictionary, global::DripSharp.PdfCarton.Cos.COSName key) {
return this.GetEmbeddedInt(embeddedDictionary, key, -1);
}

public virtual int GetEmbeddedInt(global::DripSharp.PdfCarton.Cos.COSName embeddedDictionary, global::DripSharp.PdfCarton.Cos.COSName key, int defaultValue) {
global::DripSharp.PdfCarton.Cos.COSDictionary embedded = this.GetCOSDictionary(embeddedDictionary);
return ((embedded != default!) ? embedded.GetInt(key, defaultValue) : defaultValue);
}

public virtual int GetInt(string key) {
return this.GetInt(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), -1);
}

public virtual int GetInt(global::DripSharp.PdfCarton.Cos.COSName key) {
return this.GetInt(key, -1);
}

public virtual int GetInt(string key, int defaultValue) {
return this.GetInt(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), defaultValue);
}

public virtual int GetInt(global::DripSharp.PdfCarton.Cos.COSName key, int defaultValue) {
return this.GetInt(key, (global::DripSharp.PdfCarton.Cos.COSName)default!, defaultValue);
}

public virtual int GetInt(global::DripSharp.PdfCarton.Cos.COSName firstKey, global::DripSharp.PdfCarton.Cos.COSName secondKey) {
return this.GetInt(firstKey, secondKey, -1);
}

public virtual int GetInt(global::DripSharp.PdfCarton.Cos.COSName firstKey, global::DripSharp.PdfCarton.Cos.COSName secondKey, int defaultValue) {
int retval = defaultValue;
global::DripSharp.PdfCarton.Cos.COSBase obj = this.GetDictionaryObject(firstKey, secondKey);
if ((obj is global::DripSharp.PdfCarton.Cos.COSNumber)) {
retval = ((global::DripSharp.PdfCarton.Cos.COSNumber)(obj!)).IntValue();
}
return retval;
}

public virtual long GetLong(string key) {
return this.GetLong(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), -1L);
}

public virtual long GetLong(global::DripSharp.PdfCarton.Cos.COSName key) {
return this.GetLong(key, -1L);
}

public virtual long GetLong(string key, long defaultValue) {
return this.GetLong(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), defaultValue);
}

public virtual long GetLong(global::DripSharp.PdfCarton.Cos.COSName key, long defaultValue) {
long retval = defaultValue;
global::DripSharp.PdfCarton.Cos.COSBase obj = this.GetDictionaryObject(key);
if ((obj is global::DripSharp.PdfCarton.Cos.COSNumber)) {
retval = ((global::DripSharp.PdfCarton.Cos.COSNumber)(obj!)).LongValue();
}
return retval;
}

public virtual float GetFloat(string key) {
return this.GetFloat(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), (float)(-1));
}

public virtual float GetFloat(global::DripSharp.PdfCarton.Cos.COSName key) {
return this.GetFloat(key, (float)(-1));
}

public virtual float GetFloat(string key, float defaultValue) {
return this.GetFloat(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key), defaultValue);
}

public virtual float GetFloat(global::DripSharp.PdfCarton.Cos.COSName key, float defaultValue) {
float retval = defaultValue;
global::DripSharp.PdfCarton.Cos.COSBase obj = this.GetDictionaryObject(key);
if ((obj is global::DripSharp.PdfCarton.Cos.COSNumber)) {
retval = ((global::DripSharp.PdfCarton.Cos.COSNumber)(obj!)).FloatValue();
}
return retval;
}

public virtual bool GetFlag(global::DripSharp.PdfCarton.Cos.COSName field, int bitFlag) {
int ff = this.GetInt(field, 0);
return ((ff & bitFlag) == bitFlag);
}

public virtual void RemoveItem(global::DripSharp.PdfCarton.Cos.COSName key) {
global::DripSharp.Runtime.JavaCompat.MapRemove(this.Items, key);
this.GetUpdateState().update();
}

public virtual global::DripSharp.PdfCarton.Cos.COSBase GetItem(global::DripSharp.PdfCarton.Cos.COSName key) {
return global::DripSharp.Runtime.JavaCompat.MapGet(this.Items, key);
}

public virtual global::DripSharp.PdfCarton.Cos.COSBase GetItem(string key) {
return this.GetItem(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(key));
}

public virtual global::DripSharp.PdfCarton.Cos.COSBase GetItem(global::DripSharp.PdfCarton.Cos.COSName firstKey, global::DripSharp.PdfCarton.Cos.COSName secondKey) {
global::DripSharp.PdfCarton.Cos.COSBase retval = this.GetItem(firstKey);
if (((retval == default!) && (secondKey != default!))) {
retval = this.GetItem(secondKey);
}
return retval;
}

public virtual global::System.Collections.Generic.ISet<global::DripSharp.PdfCarton.Cos.COSName> KeySet() {
return global::DripSharp.Runtime.JavaCompat.MapKeySet(this.Items);
}

public virtual global::System.Collections.Generic.ISet<global::DripSharp.Runtime.JavaMapEntry<global::DripSharp.PdfCarton.Cos.COSName, global::DripSharp.PdfCarton.Cos.COSBase>> EntrySet() {
return global::DripSharp.Runtime.JavaCompat.MapEntrySet(this.Items);
}

public virtual void ForEach(global::System.Action<global::DripSharp.PdfCarton.Cos.COSName, global::DripSharp.PdfCarton.Cos.COSBase> action) {
global::DripSharp.Runtime.JavaCompat.ForEach(this.Items, action);
}

public virtual global::System.Collections.Generic.ICollection<global::DripSharp.PdfCarton.Cos.COSBase> GetValues() {
return this.Items.Values;
}

public override void Accept(global::DripSharp.PdfCarton.Cos.ICOSVisitor visitor) {
visitor.VisitFromDictionary(this);
}

public virtual void AddAll(global::DripSharp.PdfCarton.Cos.COSDictionary dict) {
global::DripSharp.Runtime.JavaCompat.MapPutAll(this.Items, global::DripSharp.Runtime.JavaCompat.CastDictionary<global::DripSharp.PdfCarton.Cos.COSName, global::DripSharp.PdfCarton.Cos.COSBase>(dict.Items));
}

public virtual bool ContainsKey(global::DripSharp.PdfCarton.Cos.COSName name) {
return global::DripSharp.Runtime.JavaCompat.MapContainsKey(this.Items, name);
}

public virtual bool ContainsKey(string name) {
return this.ContainsKey(global::DripSharp.PdfCarton.Cos.COSName.GetPDFName(name));
}

public virtual global::DripSharp.PdfCarton.Cos.COSBase GetObjectFromPath(string objPath) {
string[] path = global::DripSharp.Runtime.JavaCompat.StringSplit(objPath, global::DripSharp.PdfCarton.Cos.COSDictionary.PATH_SEPARATOR, 0);
global::DripSharp.PdfCarton.Cos.COSBase retval = this;
foreach (string pathString in path) {
if ((retval is global::DripSharp.PdfCarton.Cos.COSArray)) {
int idx = global::DripSharp.Runtime.JavaCompat.ParseInt(pathString.Replace("\\[", "", global::System.StringComparison.Ordinal).Replace("\\]", "", global::System.StringComparison.Ordinal), 10);
retval = ((global::DripSharp.PdfCarton.Cos.COSArray)(retval!)).GetObject(idx);
} else {
if ((retval is global::DripSharp.PdfCarton.Cos.COSDictionary)) {
retval = ((global::DripSharp.PdfCarton.Cos.COSDictionary)(retval!)).GetDictionaryObject(pathString);
}
}
}
return retval;
}

public virtual global::DripSharp.PdfCarton.Cos.COSDictionary AsUnmodifiableDictionary() {
return new global::DripSharp.PdfCarton.Cos.UnmodifiableCOSDictionary(this);
}

public override string ToString() {
try {
return global::DripSharp.PdfCarton.Cos.COSDictionary.getDictionaryString(this, new global::System.Collections.Generic.List<global::DripSharp.PdfCarton.Cos.COSBase>());
} catch (global::System.IO.IOException e) {
global::Microsoft.Extensions.Logging.LoggerExtensions.LogDebug(global::DripSharp.PdfCarton.Cos.COSDictionary.LOG, (global::System.Exception)e, global::DripSharp.Runtime.JavaCompat.StringValueOf("An exception occurred trying - returning error message instead"));
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("COSDictionary{", global::DripSharp.Runtime.JavaCompat.ExceptionMessage(e)), "}");
}
}

private static string getDictionaryString(global::DripSharp.PdfCarton.Cos.COSBase @base, global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Cos.COSBase> objs) {
if ((@base == default!)) {
return "null";
}
if (global::DripSharp.Runtime.JavaCompat.CollectionContains(objs, @base)) {
return global::DripSharp.Runtime.JavaCompat.Concat("hash:", @base.GetHashCode());
}
if ((@base is global::DripSharp.PdfCarton.Cos.COSDictionary)) {
global::DripSharp.Runtime.JavaCompat.Add(objs, @base);
global::System.Text.StringBuilder sb__1375_27 = new global::System.Text.StringBuilder("COSDictionary{");
foreach (global::DripSharp.Runtime.JavaMapEntry<global::DripSharp.PdfCarton.Cos.COSName, global::DripSharp.PdfCarton.Cos.COSBase> x__1376_46 in ((global::DripSharp.PdfCarton.Cos.COSDictionary)(@base!)).EntrySet()) {
sb__1375_27.Append(global::DripSharp.Runtime.JavaCompat.StringValueOf(x__1376_46.Key));
sb__1375_27.Append(":");
sb__1375_27.Append(global::DripSharp.PdfCarton.Cos.COSDictionary.getDictionaryString(x__1376_46.Value, objs));
sb__1375_27.Append(";");
}
sb__1375_27.Append("}");
if ((@base is global::DripSharp.PdfCarton.Cos.COSStream)) {
using (global::System.IO.Stream stream = ((global::DripSharp.PdfCarton.Cos.COSStream)(@base!)).CreateRawInputStream()) {
sbyte[] b = global::DripSharp.PdfCarton.IO.IOUtils.ToByteArray(stream);
sb__1375_27.Append("COSStream{").Append(global::DripSharp.Runtime.JavaCompat.ArrayHash(b)).Append("}");
}
}
return sb__1375_27.ToString();
}
if ((@base is global::DripSharp.PdfCarton.Cos.COSArray)) {
global::DripSharp.Runtime.JavaCompat.Add(objs, @base);
global::System.Text.StringBuilder sb__1397_27 = new global::System.Text.StringBuilder("COSArray{");
foreach (global::DripSharp.PdfCarton.Cos.COSBase x__1398_26 in (global::DripSharp.PdfCarton.Cos.COSArray)(@base!)) {
sb__1397_27.Append(global::DripSharp.PdfCarton.Cos.COSDictionary.getDictionaryString(x__1398_26, objs));
sb__1397_27.Append(";");
}
sb__1397_27.Append("}");
return sb__1397_27.ToString();
}
if ((@base is global::DripSharp.PdfCarton.Cos.COSObject)) {
global::DripSharp.Runtime.JavaCompat.Add(objs, @base);
global::DripSharp.PdfCarton.Cos.COSObject obj = (global::DripSharp.PdfCarton.Cos.COSObject)(@base!);
return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("COSObject{", global::DripSharp.PdfCarton.Cos.COSDictionary.getDictionaryString((obj.IsObjectNull() ? (global::DripSharp.PdfCarton.Cos.COSBase)(global::DripSharp.PdfCarton.Cos.COSNull.Null) : obj.GetObject()), objs)), "}");
}
return global::DripSharp.Runtime.JavaCompat.StringValueOf(@base);
}

public virtual global::DripSharp.PdfCarton.Cos.COSUpdateState GetUpdateState() {
return this.updateState;
}

public virtual void GetIndirectObjectKeys(global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Cos.COSObjectKey> indirectObjects) {
this.GetIndirectObjectKeys((global::System.Collections.Generic.ICollection<global::DripSharp.PdfCarton.Cos.COSObjectKey>)(indirectObjects!));
}

public virtual void GetIndirectObjectKeys(global::System.Collections.Generic.ICollection<global::DripSharp.PdfCarton.Cos.COSObjectKey> indirectObjects) {
if ((indirectObjects == default!)) {
return;
}
global::DripSharp.PdfCarton.Cos.COSObjectKey key = this.GetKey();
if ((key != default!)) {
if (global::DripSharp.Runtime.JavaCompat.CollectionContains(indirectObjects, key)) {
return;
}
global::DripSharp.Runtime.JavaCompat.Add(indirectObjects, key);
}
foreach (global::DripSharp.Runtime.JavaMapEntry<global::DripSharp.PdfCarton.Cos.COSName, global::DripSharp.PdfCarton.Cos.COSBase> entry in global::DripSharp.Runtime.JavaCompat.MapEntrySet(this.Items)) {
global::DripSharp.PdfCarton.Cos.COSBase cosBase = entry.Value;
global::DripSharp.PdfCarton.Cos.COSObjectKey indirectObjectKey = ((cosBase is global::DripSharp.PdfCarton.Cos.COSObject) ? cosBase.GetKey() : (global::DripSharp.PdfCarton.Cos.COSObjectKey)(default!));
if ((indirectObjectKey != default!)) {
if (global::DripSharp.Runtime.JavaCompat.CollectionContains(indirectObjects, indirectObjectKey)) {
continue;
}
cosBase = ((global::DripSharp.PdfCarton.Cos.COSObject)(cosBase!)).GetObject();
}
if ((cosBase is global::DripSharp.PdfCarton.Cos.COSDictionary)) {
global::DripSharp.PdfCarton.Cos.COSName entryKey = entry.Key;
if ((!(global::DripSharp.PdfCarton.Cos.COSName.Parent.Equals(entryKey)) && !(global::DripSharp.PdfCarton.Cos.COSName.P.Equals(entryKey)))) {
((global::DripSharp.PdfCarton.Cos.COSDictionary)(cosBase!)).GetIndirectObjectKeys(indirectObjects);
}
} else {
if ((cosBase is global::DripSharp.PdfCarton.Cos.COSArray)) {
((global::DripSharp.PdfCarton.Cos.COSArray)(cosBase!)).GetIndirectObjectKeys(indirectObjects);
} else {
if ((indirectObjectKey != default!)) {
global::DripSharp.Runtime.JavaCompat.Add(indirectObjects, indirectObjectKey);
}
}
}
}
}

public virtual void ResetImportedObjectKeys() {
this.ResetObjectKeys(new global::System.Collections.Generic.HashSet<global::DripSharp.PdfCarton.Cos.COSObjectKey>()).Clear();
}

protected internal virtual global::System.Collections.Generic.ICollection<global::DripSharp.PdfCarton.Cos.COSObjectKey> ResetObjectKeys(global::System.Collections.Generic.ICollection<global::DripSharp.PdfCarton.Cos.COSObjectKey> indirectObjects) {
if ((indirectObjects == default!)) {
return indirectObjects;
}
global::DripSharp.PdfCarton.Cos.COSObjectKey key = this.GetKey();
if ((key != default!)) {
if (global::DripSharp.Runtime.JavaCompat.CollectionContains(indirectObjects, key)) {
return indirectObjects;
}
global::DripSharp.Runtime.JavaCompat.Add(indirectObjects, key);
this.SetKey((global::DripSharp.PdfCarton.Cos.COSObjectKey)default!);
}
foreach (global::DripSharp.Runtime.JavaMapEntry<global::DripSharp.PdfCarton.Cos.COSName, global::DripSharp.PdfCarton.Cos.COSBase> entry in global::DripSharp.Runtime.JavaCompat.MapEntrySet(this.Items)) {
global::DripSharp.PdfCarton.Cos.COSBase cosBase = entry.Value;
global::DripSharp.PdfCarton.Cos.COSObjectKey indirectObjectKey = ((cosBase is global::DripSharp.PdfCarton.Cos.COSObject) ? cosBase.GetKey() : (global::DripSharp.PdfCarton.Cos.COSObjectKey)(default!));
if ((indirectObjectKey != default!)) {
if (global::DripSharp.Runtime.JavaCompat.CollectionContains(indirectObjects, indirectObjectKey)) {
continue;
}
cosBase = ((global::DripSharp.PdfCarton.Cos.COSObject)(cosBase!)).GetObject();
entry.Value.SetKey((global::DripSharp.PdfCarton.Cos.COSObjectKey)default!);
}
if ((cosBase is global::DripSharp.PdfCarton.Cos.COSDictionary)) {
global::DripSharp.PdfCarton.Cos.COSName entryKey = entry.Key;
if ((!(global::DripSharp.PdfCarton.Cos.COSName.Parent.Equals(entryKey)) && !(global::DripSharp.PdfCarton.Cos.COSName.P.Equals(entryKey)))) {
((global::DripSharp.PdfCarton.Cos.COSDictionary)(cosBase!)).ResetObjectKeys(indirectObjects);
}
} else {
if ((cosBase is global::DripSharp.PdfCarton.Cos.COSArray)) {
((global::DripSharp.PdfCarton.Cos.COSArray)(cosBase!)).ResetObjectKeys(indirectObjects);
} else {
if ((indirectObjectKey != default!)) {
global::DripSharp.Runtime.JavaCompat.Add(indirectObjects, indirectObjectKey);
}
}
}
}
return indirectObjects;
}
}
