// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/contentstream/operator/graphics/CloseFillNonZeroAndStrokePath.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Contentstream.@Operator.Graphics;

public sealed class CloseFillNonZeroAndStrokePath
: global::DripSharp.PdfCarton.Contentstream.@Operator.Graphics.GraphicsOperatorProcessor {
  public CloseFillNonZeroAndStrokePath(global::DripSharp.PdfCarton.Contentstream.PDFGraphicsStreamEngine context)
  : base(context) {

  }

  public override void Process(global::DripSharp.PdfCarton.Contentstream.@Operator.Operator @operator,
    global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Cos.COSBase> operands) {
    global::DripSharp.PdfCarton.Contentstream.PDFStreamEngine context = this.GetContext();
    context.ProcessOperator(global::DripSharp.PdfCarton.Contentstream.@Operator.OperatorName.ClosePath,
      operands);
    context.ProcessOperator(global::DripSharp.PdfCarton.Contentstream.@Operator.OperatorName.FillNonZeroAndStroke,
      operands);
  }

  public override string GetName() {
    return global::DripSharp.PdfCarton.Contentstream.@Operator.OperatorName.CloseFillNonZeroAndStroke;
  }
}
