// <auto-generated />
// Mechanically translated from: org/apache/xmpbox/type/FontType.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Xmp.Type;

[global::DripSharp.PdfCarton.Xmp.Type.StructuredTypeAttribute("http://ns.adobe.com/xap/1.0/sType/Font#",
  "stFnt")]
public class FontType : global::DripSharp.PdfCarton.Xmp.Type.AbstractStructuredType {
  [global::DripSharp.PdfCarton.Xmp.Type.PropertyTypeAttribute("Text", "Seq")]
  public const string ChildFontFiles = "childFontFiles";

  [global::DripSharp.PdfCarton.Xmp.Type.PropertyTypeAttribute("Boolean", "Simple")]
  public const string Composite = "composite";

  [global::DripSharp.PdfCarton.Xmp.Type.PropertyTypeAttribute("Text", "Simple")]
  public const string FontFace = "fontFace";

  [global::DripSharp.PdfCarton.Xmp.Type.PropertyTypeAttribute("Text", "Simple")]
  public const string FontFamily = "fontFamily";

  [global::DripSharp.PdfCarton.Xmp.Type.PropertyTypeAttribute("Text", "Simple")]
  public const string FontFileName = "fontFileName";

  [global::DripSharp.PdfCarton.Xmp.Type.PropertyTypeAttribute("Text", "Simple")]
  public const string FontName = "fontName";

  [global::DripSharp.PdfCarton.Xmp.Type.PropertyTypeAttribute("Choice", "Simple")]
  public const string __field_FontType = "fontType";

  [global::DripSharp.PdfCarton.Xmp.Type.PropertyTypeAttribute("Text", "Simple")]
  public const string VersionString = "versionString";

  public FontType(global::DripSharp.PdfCarton.Xmp.XMPMetadata metadata) : base(metadata) {

  }
}
