// <auto-generated />
// Mechanically translated from: org/apache/xmpbox/type/LayerType.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Xmp.Type;

[global::DripSharp.PdfCarton.Xmp.Type.StructuredTypeAttribute("http://ns.adobe.com/photoshop/1.0/",
  "photoshop")]
public class LayerType : global::DripSharp.PdfCarton.Xmp.Type.AbstractStructuredType {
  [global::DripSharp.PdfCarton.Xmp.Type.PropertyTypeAttribute("Text", "Simple")]
  public const string LayerName = "LayerName";

  [global::DripSharp.PdfCarton.Xmp.Type.PropertyTypeAttribute("Text", "Simple")]
  public const string LayerText = "LayerText";

  public LayerType(global::DripSharp.PdfCarton.Xmp.XMPMetadata metadata) : base(metadata) {
    this.SetAttribute(new global::DripSharp.PdfCarton.Xmp.Type.Attribute(global::DripSharp.PdfCarton.Xmp.XmpConstants.RdfNamespace,
      "parseType", "Resource"));
  }

  public virtual string GetLayerName() {
    global::DripSharp.PdfCarton.Xmp.Type.AbstractField absProp
      = this.GetFirstEquivalentProperty(global::DripSharp.PdfCarton.Xmp.Type.LayerType.LayerName,
      typeof(global::DripSharp.PdfCarton.Xmp.Type.TextType));
    if ((absProp != default!)) {
      return ((global::DripSharp.PdfCarton.Xmp.Type.TextType)(absProp!)).GetStringValue();
    }
    return default!;
  }

  public virtual void SetLayerName(string image) {
    this.AddProperty(this.CreateTextType(global::DripSharp.PdfCarton.Xmp.Type.LayerType.LayerName,
      image));
  }

  public virtual string GetLayerText() {
    global::DripSharp.PdfCarton.Xmp.Type.AbstractField absProp
      = this.GetFirstEquivalentProperty(global::DripSharp.PdfCarton.Xmp.Type.LayerType.LayerText,
      typeof(global::DripSharp.PdfCarton.Xmp.Type.TextType));
    if ((absProp != default!)) {
      return ((global::DripSharp.PdfCarton.Xmp.Type.TextType)(absProp!)).GetStringValue();
    }
    return default!;
  }

  public virtual void SetLayerText(string image) {
    this.AddProperty(this.CreateTextType(global::DripSharp.PdfCarton.Xmp.Type.LayerType.LayerText,
      image));
  }
}
