// <auto-generated />
// Mechanically translated from: org/apache/xmpbox/type/PropertyType.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Xmp.Type;

public interface PropertyType {
public global::DripSharp.PdfCarton.Xmp.Type.Types Type();

public global::DripSharp.PdfCarton.Xmp.Type.Cardinality Card();
}

[global::System.AttributeUsage(global::System.AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
internal sealed class PropertyTypeAttribute : global::System.Attribute, PropertyType {
private readonly string __type;
private readonly string __card;

public PropertyTypeAttribute(string type, string card) {
this.__type = type;
this.__card = card;
}

public global::DripSharp.PdfCarton.Xmp.Type.Types Type() {
return global::DripSharp.PdfCarton.Xmp.Type.Types.valueOf(this.__type);
}

public global::DripSharp.PdfCarton.Xmp.Type.Cardinality Card() {
return global::DripSharp.PdfCarton.Xmp.Type.Cardinality.valueOf(this.__card);
}
}
