// <auto-generated />
// Mechanically translated from: org/apache/xmpbox/type/Types.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Xmp.Type;

public sealed class Types {
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Structured")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(0)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Structured = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, (global::DripSharp.PdfCarton.Xmp.Type.Types)default!, (global::System.Type)default!);

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("DefinedType")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(1)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types DefinedType = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, (global::DripSharp.PdfCarton.Xmp.Type.Types)default!, (global::System.Type)default!);

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Text")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(2)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Text = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, (global::DripSharp.PdfCarton.Xmp.Type.Types)default!, typeof(global::DripSharp.PdfCarton.Xmp.Type.TextType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Date")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(3)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Date = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, (global::DripSharp.PdfCarton.Xmp.Type.Types)default!, typeof(global::DripSharp.PdfCarton.Xmp.Type.DateType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Boolean")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(4)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Boolean = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, (global::DripSharp.PdfCarton.Xmp.Type.Types)default!, typeof(global::DripSharp.PdfCarton.Xmp.Type.BooleanType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Integer")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(5)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Integer = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, (global::DripSharp.PdfCarton.Xmp.Type.Types)default!, typeof(global::DripSharp.PdfCarton.Xmp.Type.IntegerType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Real")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(6)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Real = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, (global::DripSharp.PdfCarton.Xmp.Type.Types)default!, typeof(global::DripSharp.PdfCarton.Xmp.Type.RealType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("GPSCoordinate")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(7)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types GPSCoordinate = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, global::DripSharp.PdfCarton.Xmp.Type.Types.Text, typeof(global::DripSharp.PdfCarton.Xmp.Type.TextType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("ProperName")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(8)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types ProperName = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, global::DripSharp.PdfCarton.Xmp.Type.Types.Text, typeof(global::DripSharp.PdfCarton.Xmp.Type.ProperNameType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Locale")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(9)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Locale = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, global::DripSharp.PdfCarton.Xmp.Type.Types.Text, typeof(global::DripSharp.PdfCarton.Xmp.Type.LocaleType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("AgentName")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(10)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types AgentName = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, global::DripSharp.PdfCarton.Xmp.Type.Types.Text, typeof(global::DripSharp.PdfCarton.Xmp.Type.AgentNameType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("GUID")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(11)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Guid = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, global::DripSharp.PdfCarton.Xmp.Type.Types.Text, typeof(global::DripSharp.PdfCarton.Xmp.Type.GUIDType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("XPath")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(12)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types XPath = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, global::DripSharp.PdfCarton.Xmp.Type.Types.Text, typeof(global::DripSharp.PdfCarton.Xmp.Type.XPathType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Part")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(13)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Part = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, global::DripSharp.PdfCarton.Xmp.Type.Types.Text, typeof(global::DripSharp.PdfCarton.Xmp.Type.PartType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("URL")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(14)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Url = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, global::DripSharp.PdfCarton.Xmp.Type.Types.Text, typeof(global::DripSharp.PdfCarton.Xmp.Type.URLType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("URI")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(15)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Uri = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, global::DripSharp.PdfCarton.Xmp.Type.Types.Text, typeof(global::DripSharp.PdfCarton.Xmp.Type.URIType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Choice")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(16)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Choice = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, global::DripSharp.PdfCarton.Xmp.Type.Types.Text, typeof(global::DripSharp.PdfCarton.Xmp.Type.ChoiceType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("MIMEType")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(17)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types MIMEType = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, global::DripSharp.PdfCarton.Xmp.Type.Types.Text, typeof(global::DripSharp.PdfCarton.Xmp.Type.MIMEType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("LangAlt")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(18)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types LangAlt = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, global::DripSharp.PdfCarton.Xmp.Type.Types.Text, typeof(global::DripSharp.PdfCarton.Xmp.Type.TextType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("RenditionClass")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(19)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types RenditionClass = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, global::DripSharp.PdfCarton.Xmp.Type.Types.Text, typeof(global::DripSharp.PdfCarton.Xmp.Type.RenditionClassType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Rational")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(20)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Rational = new global::DripSharp.PdfCarton.Xmp.Type.Types(true, global::DripSharp.PdfCarton.Xmp.Type.Types.Text, typeof(global::DripSharp.PdfCarton.Xmp.Type.RationalType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Colorant")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(21)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Colorant = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.ColorantType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Font")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(22)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Font = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.FontType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Layer")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(23)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Layer = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.LayerType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Thumbnail")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(24)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Thumbnail = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.ThumbnailType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("ResourceEvent")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(25)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types ResourceEvent = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.ResourceEventType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("ResourceRef")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(26)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types ResourceRef = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.ResourceRefType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Version")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(27)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Version = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.VersionType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("PDFASchema")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(28)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types PDFASchema = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.PDFASchemaType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("PDFAField")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(29)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types PDFAField = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.PDFAFieldType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("PDFAProperty")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(30)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types PDFAProperty = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.PDFAPropertyType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("PDFAType")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(31)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types PDFAType = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.PDFATypeType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Job")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(32)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Job = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.JobType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("OECF")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(33)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Oecf = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.OECFType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("CFAPattern")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(34)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types CFAPattern = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.CFAPatternType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("DeviceSettings")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(35)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types DeviceSettings = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.DeviceSettingsType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Flash")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(36)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Flash = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.FlashType));

[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumNameAttribute("Dimensions")]
[global::DripSharp.PdfCarton.Runtime.Xmp.JavaEnumOrdinalAttribute(37)]
public static readonly global::DripSharp.PdfCarton.Xmp.Type.Types Dimensions = new global::DripSharp.PdfCarton.Xmp.Type.Types(false, global::DripSharp.PdfCarton.Xmp.Type.Types.Structured, typeof(global::DripSharp.PdfCarton.Xmp.Type.DimensionsType));

private readonly bool simple = default;

private readonly global::DripSharp.PdfCarton.Xmp.Type.Types basic = null!;

private readonly global::System.Type clz = null!;

private Types(bool s, global::DripSharp.PdfCarton.Xmp.Type.Types b, global::System.Type c) {
this.simple = s;
this.basic = b;
this.clz = c;
}

public bool IsSimple() {
return this.simple;
}

public bool IsBasic() {
return (this.basic == default!);
}

public bool IsStructured() {
return (this.basic == global::DripSharp.PdfCarton.Xmp.Type.Types.Structured);
}

public bool IsDefined() {
return (this == global::DripSharp.PdfCarton.Xmp.Type.Types.DefinedType);
}

public global::DripSharp.PdfCarton.Xmp.Type.Types GetBasic() {
return this.basic;
}

public global::System.Type GetImplementingClass() {
return this.clz;
}

public static Types[] values() => global::DripSharp.PdfCarton.Runtime.Xmp.JavaCompat.EnumValues<Types>();
public static Types valueOf(string name) => global::DripSharp.PdfCarton.Runtime.Xmp.JavaCompat.EnumValueOf<Types>(name);

public override string ToString() => global::DripSharp.PdfCarton.Runtime.Xmp.JavaCompat.EnumName(this);
}
