// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/preflight/action/UriAction.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Preflight.Action;

public class UriAction : global::DripSharp.PdfCarton.Preflight.Action.AbstractActionManager {
  public UriAction(global::DripSharp.PdfCarton.Preflight.Action.ActionManagerFactory amFact,
    global::DripSharp.PdfCarton.Cos.COSDictionary adict,
    global::DripSharp.PdfCarton.Preflight.PreflightContext ctx, string aaKey) : base(amFact, adict,
    ctx, aaKey) {

  }

  protected internal override bool InnerValid() {
    global::DripSharp.PdfCarton.Cos.COSBase uri
      = this.ActionDictionary.GetDictionaryObject(global::DripSharp.PdfCarton.Cos.COSName.Uri);
    if ((uri == default!)) {
      base.Context.AddValidationError(new global::DripSharp.PdfCarton.Preflight.ValidationResult.ValidationError(global::DripSharp.PdfCarton.Preflight.PreflightConstants.ErrorActionMisingKey,
        "URI entry is mandatory for the UriAction"));
      return false;
    }
    if (!((uri is global::DripSharp.PdfCarton.Cos.COSString))) {
      base.Context.AddValidationError(new global::DripSharp.PdfCarton.Preflight.ValidationResult.ValidationError(global::DripSharp.PdfCarton.Preflight.PreflightConstants.ErrorActionInvalidType,
        "URI entry should be a string"));
      return false;
    }
    return true;
  }
}
