// <auto-generated />
// Mechanically translated from: org/apache/fontbox/afm/AFMParser.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Fonts.Afm;

public class AFMParser {
public const string Comment = "Comment";

public const string StartFontMetrics = "StartFontMetrics";

public const string EndFontMetrics = "EndFontMetrics";

public const string FontName = "FontName";

public const string FullName = "FullName";

public const string FamilyName = "FamilyName";

public const string Weight = "Weight";

public const string FontBbox = "FontBBox";

public const string Version = "Version";

public const string Notice = "Notice";

public const string EncodingScheme = "EncodingScheme";

public const string MappingScheme = "MappingScheme";

public const string EscChar = "EscChar";

public const string CharacterSet = "CharacterSet";

public const string Characters = "Characters";

public const string IsBaseFont = "IsBaseFont";

public const string VVector = "VVector";

public const string IsFixedV = "IsFixedV";

public const string CapHeight = "CapHeight";

public const string XHeight = "XHeight";

public const string Ascender = "Ascender";

public const string Descender = "Descender";

public const string UnderlinePosition = "UnderlinePosition";

public const string UnderlineThickness = "UnderlineThickness";

public const string ItalicAngle = "ItalicAngle";

public const string CharWidth = "CharWidth";

public const string IsFixedPitch = "IsFixedPitch";

public const string StartCharMetrics = "StartCharMetrics";

public const string EndCharMetrics = "EndCharMetrics";

public const string CharmetricsC = "C";

public const string CharmetricsCh = "CH";

public const string CharmetricsWx = "WX";

public const string CharmetricsW0x = "W0X";

public const string CharmetricsW1x = "W1X";

public const string CharmetricsWy = "WY";

public const string CharmetricsW0y = "W0Y";

public const string CharmetricsW1y = "W1Y";

public const string CharmetricsW = "W";

public const string CharmetricsW0 = "W0";

public const string CharmetricsW1 = "W1";

public const string CharmetricsVv = "VV";

public const string CharmetricsN = "N";

public const string CharmetricsB = "B";

public const string CharmetricsL = "L";

public const string StdHw = "StdHW";

public const string StdVw = "StdVW";

public const string StartTrackKern = "StartTrackKern";

public const string EndTrackKern = "EndTrackKern";

public const string StartKernData = "StartKernData";

public const string EndKernData = "EndKernData";

public const string StartKernPairs = "StartKernPairs";

public const string EndKernPairs = "EndKernPairs";

public const string StartKernPairs0 = "StartKernPairs0";

public const string StartKernPairs1 = "StartKernPairs1";

public const string StartComposites = "StartComposites";

public const string EndComposites = "EndComposites";

public const string Cc = "CC";

public const string Pcc = "PCC";

public const string KernPairKp = "KP";

public const string KernPairKph = "KPH";

public const string KernPairKpx = "KPX";

public const string KernPairKpy = "KPY";

private const int BITS_IN_HEX = 16;

private readonly global::System.IO.Stream input = null!;

public AFMParser(global::System.IO.Stream @in) {
this.input = @in;
}

public virtual global::DripSharp.PdfCarton.Fonts.Afm.FontMetrics Parse() {
return this.Parse(false);
}

public virtual global::DripSharp.PdfCarton.Fonts.Afm.FontMetrics Parse(bool reducedDataset) {
try {
return this.parseFontMetric(reducedDataset);
} catch (global::System.InvalidOperationException ex) {
throw new global::System.IO.IOException(null, ex);
}
}

private global::DripSharp.PdfCarton.Fonts.Afm.FontMetrics parseFontMetric(bool reducedDataset) {
this.readCommand(global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.StartFontMetrics);
global::DripSharp.PdfCarton.Fonts.Afm.FontMetrics fontMetrics = new global::DripSharp.PdfCarton.Fonts.Afm.FontMetrics();
fontMetrics.SetAFMVersion(this.readFloat());
string nextCommand;
bool charMetricsRead = false;
while (!(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Equals(global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.EndFontMetrics, (nextCommand = this.readString())))) {
switch (nextCommand) {
case var __case_354_18_0 when global::System.Object.Equals(__case_354_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.FontName):
fontMetrics.SetFontName(this.readLine());
break;
case var __case_357_18_0 when global::System.Object.Equals(__case_357_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.FullName):
fontMetrics.SetFullName(this.readLine());
break;
case var __case_360_18_0 when global::System.Object.Equals(__case_360_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.FamilyName):
fontMetrics.SetFamilyName(this.readLine());
break;
case var __case_363_18_0 when global::System.Object.Equals(__case_363_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.Weight):
fontMetrics.SetWeight(this.readLine());
break;
case var __case_366_18_0 when global::System.Object.Equals(__case_366_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.FontBbox):
global::DripSharp.PdfCarton.Fonts.Util.BoundingBox bBox = new global::DripSharp.PdfCarton.Fonts.Util.BoundingBox();
bBox.SetLowerLeftX(this.readFloat());
bBox.SetLowerLeftY(this.readFloat());
bBox.SetUpperRightX(this.readFloat());
bBox.SetUpperRightY(this.readFloat());
fontMetrics.SetFontBBox(bBox);
break;
case var __case_374_18_0 when global::System.Object.Equals(__case_374_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.Version):
fontMetrics.SetFontVersion(this.readLine());
break;
case var __case_377_18_0 when global::System.Object.Equals(__case_377_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.Notice):
fontMetrics.SetNotice(this.readLine());
break;
case var __case_380_18_0 when global::System.Object.Equals(__case_380_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.EncodingScheme):
fontMetrics.SetEncodingScheme(this.readLine());
break;
case var __case_383_18_0 when global::System.Object.Equals(__case_383_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.MappingScheme):
fontMetrics.SetMappingScheme(this.readInt());
break;
case var __case_386_18_0 when global::System.Object.Equals(__case_386_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.EscChar):
fontMetrics.SetEscChar(this.readInt());
break;
case var __case_389_18_0 when global::System.Object.Equals(__case_389_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharacterSet):
fontMetrics.SetCharacterSet(this.readLine());
break;
case var __case_392_18_0 when global::System.Object.Equals(__case_392_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.Characters):
fontMetrics.SetCharacters(this.readInt());
break;
case var __case_395_18_0 when global::System.Object.Equals(__case_395_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.IsBaseFont):
fontMetrics.SetIsBaseFont(this.readBoolean());
break;
case var __case_398_18_0 when global::System.Object.Equals(__case_398_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.VVector):
float[] vector = new float[2];
vector[0] = this.readFloat();
vector[1] = this.readFloat();
fontMetrics.SetVVector(vector);
break;
case var __case_404_18_0 when global::System.Object.Equals(__case_404_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.IsFixedV):
fontMetrics.SetIsFixedV(this.readBoolean());
break;
case var __case_407_18_0 when global::System.Object.Equals(__case_407_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CapHeight):
fontMetrics.SetCapHeight(this.readFloat());
break;
case var __case_410_18_0 when global::System.Object.Equals(__case_410_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.XHeight):
fontMetrics.SetXHeight(this.readFloat());
break;
case var __case_413_18_0 when global::System.Object.Equals(__case_413_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.Ascender):
fontMetrics.SetAscender(this.readFloat());
break;
case var __case_416_18_0 when global::System.Object.Equals(__case_416_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.Descender):
fontMetrics.SetDescender(this.readFloat());
break;
case var __case_419_18_0 when global::System.Object.Equals(__case_419_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.StdHw):
fontMetrics.SetStandardHorizontalWidth(this.readFloat());
break;
case var __case_422_18_0 when global::System.Object.Equals(__case_422_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.StdVw):
fontMetrics.SetStandardVerticalWidth(this.readFloat());
break;
case var __case_425_18_0 when global::System.Object.Equals(__case_425_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.Comment):
fontMetrics.AddComment(this.readLine());
break;
case var __case_428_18_0 when global::System.Object.Equals(__case_428_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.UnderlinePosition):
fontMetrics.SetUnderlinePosition(this.readFloat());
break;
case var __case_431_18_0 when global::System.Object.Equals(__case_431_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.UnderlineThickness):
fontMetrics.SetUnderlineThickness(this.readFloat());
break;
case var __case_434_18_0 when global::System.Object.Equals(__case_434_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.ItalicAngle):
fontMetrics.SetItalicAngle(this.readFloat());
break;
case var __case_437_18_0 when global::System.Object.Equals(__case_437_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharWidth):
float[] widths = new float[2];
widths[0] = this.readFloat();
widths[1] = this.readFloat();
fontMetrics.SetCharWidth(widths);
break;
case var __case_443_18_0 when global::System.Object.Equals(__case_443_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.IsFixedPitch):
fontMetrics.SetFixedPitch(this.readBoolean());
break;
case var __case_446_18_0 when global::System.Object.Equals(__case_446_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.StartCharMetrics):
charMetricsRead = this.parseCharMetrics(fontMetrics);
break;
case var __case_449_18_0 when global::System.Object.Equals(__case_449_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.StartKernData):
if (!reducedDataset) {
this.parseKernData(fontMetrics);
}
break;
case var __case_455_18_0 when global::System.Object.Equals(__case_455_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.StartComposites):
if (!reducedDataset) {
this.parseComposites(fontMetrics);
}
break;
default:
if ((!reducedDataset || !charMetricsRead)) {
throw new global::System.IO.IOException(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat("Unknown AFM key '", nextCommand), "'"));
}
break;
}
}
return fontMetrics;
}

private void parseKernData(global::DripSharp.PdfCarton.Fonts.Afm.FontMetrics fontMetrics) {
string nextCommand;
while (!(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Equals((nextCommand = this.readString()), global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.EndKernData))) {
switch (nextCommand) {
case var __case_485_18_0 when global::System.Object.Equals(__case_485_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.StartTrackKern):
int countTrackKern = this.readInt();
for (int i = 0; (i < countTrackKern); i++) {
fontMetrics.AddTrackKern(new global::DripSharp.PdfCarton.Fonts.Afm.TrackKern(this.readInt(), this.readFloat(), this.readFloat(), this.readFloat(), this.readFloat()));
}
this.readCommand(global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.EndTrackKern);
break;
case var __case_494_18_0 when global::System.Object.Equals(__case_494_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.StartKernPairs):
this.parseKernPairs(fontMetrics);
break;
case var __case_497_18_0 when global::System.Object.Equals(__case_497_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.StartKernPairs0):
this.parseKernPairs0(fontMetrics);
break;
case var __case_500_18_0 when global::System.Object.Equals(__case_500_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.StartKernPairs1):
this.parseKernPairs1(fontMetrics);
break;
default:
throw new global::System.IO.IOException(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat("Unknown kerning data type '", nextCommand), "'"));
}
}
}

private void parseKernPairs(global::DripSharp.PdfCarton.Fonts.Afm.FontMetrics fontMetrics) {
int countKernPairs = this.readInt();
for (int i = 0; (i < countKernPairs); i++) {
fontMetrics.AddKernPair(this.parseKernPair());
}
this.readCommand(global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.EndKernPairs);
}

private void parseKernPairs0(global::DripSharp.PdfCarton.Fonts.Afm.FontMetrics fontMetrics) {
int countKernPairs = this.readInt();
for (int i = 0; (i < countKernPairs); i++) {
fontMetrics.AddKernPair0(this.parseKernPair());
}
this.readCommand(global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.EndKernPairs);
}

private void parseKernPairs1(global::DripSharp.PdfCarton.Fonts.Afm.FontMetrics fontMetrics) {
int countKernPairs = this.readInt();
for (int i = 0; (i < countKernPairs); i++) {
fontMetrics.AddKernPair1(this.parseKernPair());
}
this.readCommand(global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.EndKernPairs);
}

private global::DripSharp.PdfCarton.Fonts.Afm.KernPair parseKernPair() {
string cmd = this.readString();
switch (cmd) {
case var __case_551_14_0 when global::System.Object.Equals(__case_551_14_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.KernPairKp):
return new global::DripSharp.PdfCarton.Fonts.Afm.KernPair(this.readString(), this.readString(), this.readFloat(), this.readFloat());
case var __case_554_14_0 when global::System.Object.Equals(__case_554_14_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.KernPairKph):
return new global::DripSharp.PdfCarton.Fonts.Afm.KernPair(this.hexToString(this.readString()), this.hexToString(this.readString()), this.readFloat(), this.readFloat());
case var __case_557_14_0 when global::System.Object.Equals(__case_557_14_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.KernPairKpx):
return new global::DripSharp.PdfCarton.Fonts.Afm.KernPair(this.readString(), this.readString(), this.readFloat(), (float)(0));
case var __case_560_14_0 when global::System.Object.Equals(__case_560_14_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.KernPairKpy):
return new global::DripSharp.PdfCarton.Fonts.Afm.KernPair(this.readString(), this.readString(), (float)(0), this.readFloat());
default:
throw new global::System.IO.IOException(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat("Error expected kern pair command actual='", cmd), "'"));
}
}

private string hexToString(string hexToString) {
if ((hexToString.Length < 2)) {
throw new global::System.IO.IOException(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat("Error: Expected hex string of length >= 2 not='", hexToString));
}
if ((((int)(hexToString[0]) != (int)('<')) || ((int)(hexToString[(hexToString.Length - 1)]) != (int)('>')))) {
throw new global::System.IO.IOException(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat("String should be enclosed by angle brackets '", hexToString), "'"));
}
string hexString = global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.StringSubstring(hexToString, 1, (hexToString.Length - 1));
sbyte[] data = new sbyte[(hexString.Length / 2)];
for (int i = 0; (i < hexString.Length); i += 2) {
string hex = global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.CodePointToString(hexString[i]), hexString[(i + 1)]);
data[(i / 2)] = unchecked((sbyte)((sbyte)(this.parseInt(hex, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.BITS_IN_HEX))));
}
return global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.NewString(data, global::DripSharp.PdfCarton.Runtime.Fonts.JavaStandardCharsets.ISO88591);
}

private void parseComposites(global::DripSharp.PdfCarton.Fonts.Afm.FontMetrics fontMetrics) {
int countComposites = this.readInt();
for (int i = 0; (i < countComposites); i++) {
fontMetrics.AddComposite(this.parseComposite());
}
this.readCommand(global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.EndComposites);
}

private global::DripSharp.PdfCarton.Fonts.Afm.Composite parseComposite() {
string partData = this.readLine();
global::DripSharp.PdfCarton.Runtime.Fonts.JavaStringTokenizer tokenizer = new global::DripSharp.PdfCarton.Runtime.Fonts.JavaStringTokenizer(partData, " ;");
string cc = tokenizer.nextToken();
if (!(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Equals(cc, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.Cc))) {
throw new global::System.IO.IOException(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat("Expected '", global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.Cc), "' actual='"), cc), "'"));
}
string name = tokenizer.nextToken();
global::DripSharp.PdfCarton.Fonts.Afm.Composite composite = new global::DripSharp.PdfCarton.Fonts.Afm.Composite(name);
int partCount = this.parseInt(tokenizer.nextToken());
for (int i = 0; (i < partCount); i++) {
string pcc = tokenizer.nextToken();
if (!(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Equals(pcc, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.Pcc))) {
throw new global::System.IO.IOException(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat("Expected '", global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.Pcc), "' actual='"), pcc), "'"));
}
string partName = tokenizer.nextToken();
int x = this.parseInt(tokenizer.nextToken());
int y = this.parseInt(tokenizer.nextToken());
composite.AddPart(new global::DripSharp.PdfCarton.Fonts.Afm.CompositePart(partName, x, y));
}
return composite;
}

private bool parseCharMetrics(global::DripSharp.PdfCarton.Fonts.Afm.FontMetrics fontMetrics) {
int countMetrics = this.readInt();
for (int i = 0; (i < countMetrics); i++) {
fontMetrics.AddCharMetric(this.parseCharMetric());
}
this.readCommand(global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.EndCharMetrics);
return true;
}

private global::DripSharp.PdfCarton.Fonts.Afm.CharMetric parseCharMetric() {
global::DripSharp.PdfCarton.Fonts.Afm.CharMetric charMetric = new global::DripSharp.PdfCarton.Fonts.Afm.CharMetric();
string metrics = this.readLine();
global::DripSharp.PdfCarton.Runtime.Fonts.JavaStringTokenizer metricsTokenizer = new global::DripSharp.PdfCarton.Runtime.Fonts.JavaStringTokenizer(metrics);
while (metricsTokenizer.hasMoreTokens()) {
string nextCommand = metricsTokenizer.nextToken();
switch (nextCommand) {
case var __case_674_18_0 when global::System.Object.Equals(__case_674_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharmetricsC):
string charCodeC = metricsTokenizer.nextToken();
charMetric.SetCharacterCode(this.parseInt(charCodeC));
this.verifySemicolon(metricsTokenizer);
break;
case var __case_679_18_0 when global::System.Object.Equals(__case_679_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharmetricsWx):
charMetric.SetWx(this.parseFloat(metricsTokenizer.nextToken()));
this.verifySemicolon(metricsTokenizer);
break;
case var __case_683_18_0 when global::System.Object.Equals(__case_683_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharmetricsN):
charMetric.SetName(metricsTokenizer.nextToken());
this.verifySemicolon(metricsTokenizer);
break;
case var __case_687_18_0 when global::System.Object.Equals(__case_687_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharmetricsB):
global::DripSharp.PdfCarton.Fonts.Util.BoundingBox box = new global::DripSharp.PdfCarton.Fonts.Util.BoundingBox();
box.SetLowerLeftX(this.parseFloat(metricsTokenizer.nextToken()));
box.SetLowerLeftY(this.parseFloat(metricsTokenizer.nextToken()));
box.SetUpperRightX(this.parseFloat(metricsTokenizer.nextToken()));
box.SetUpperRightY(this.parseFloat(metricsTokenizer.nextToken()));
charMetric.SetBoundingBox(box);
this.verifySemicolon(metricsTokenizer);
break;
case var __case_696_18_0 when global::System.Object.Equals(__case_696_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharmetricsL):
global::DripSharp.PdfCarton.Fonts.Afm.Ligature lig = new global::DripSharp.PdfCarton.Fonts.Afm.Ligature(metricsTokenizer.nextToken(), metricsTokenizer.nextToken());
charMetric.AddLigature(lig);
this.verifySemicolon(metricsTokenizer);
break;
case var __case_702_18_0 when global::System.Object.Equals(__case_702_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharmetricsCh):
string charCodeCH = metricsTokenizer.nextToken();
charMetric.SetCharacterCode(this.parseInt(charCodeCH, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.BITS_IN_HEX));
this.verifySemicolon(metricsTokenizer);
break;
case var __case_709_18_0 when global::System.Object.Equals(__case_709_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharmetricsW0x):
charMetric.SetW0x(this.parseFloat(metricsTokenizer.nextToken()));
this.verifySemicolon(metricsTokenizer);
break;
case var __case_713_18_0 when global::System.Object.Equals(__case_713_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharmetricsW1x):
charMetric.SetW1x(this.parseFloat(metricsTokenizer.nextToken()));
this.verifySemicolon(metricsTokenizer);
break;
case var __case_717_18_0 when global::System.Object.Equals(__case_717_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharmetricsWy):
charMetric.SetWy(this.parseFloat(metricsTokenizer.nextToken()));
this.verifySemicolon(metricsTokenizer);
break;
case var __case_721_18_0 when global::System.Object.Equals(__case_721_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharmetricsW0y):
charMetric.SetW0y(this.parseFloat(metricsTokenizer.nextToken()));
this.verifySemicolon(metricsTokenizer);
break;
case var __case_725_18_0 when global::System.Object.Equals(__case_725_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharmetricsW1y):
charMetric.SetW1y(this.parseFloat(metricsTokenizer.nextToken()));
this.verifySemicolon(metricsTokenizer);
break;
case var __case_729_18_0 when global::System.Object.Equals(__case_729_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharmetricsW):
float[] w = new float[2];
w[0] = this.parseFloat(metricsTokenizer.nextToken());
w[1] = this.parseFloat(metricsTokenizer.nextToken());
charMetric.SetW(w);
this.verifySemicolon(metricsTokenizer);
break;
case var __case_736_18_0 when global::System.Object.Equals(__case_736_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharmetricsW0):
float[] w0 = new float[2];
w0[0] = this.parseFloat(metricsTokenizer.nextToken());
w0[1] = this.parseFloat(metricsTokenizer.nextToken());
charMetric.SetW0(w0);
this.verifySemicolon(metricsTokenizer);
break;
case var __case_743_18_0 when global::System.Object.Equals(__case_743_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharmetricsW1):
float[] w1 = new float[2];
w1[0] = this.parseFloat(metricsTokenizer.nextToken());
w1[1] = this.parseFloat(metricsTokenizer.nextToken());
charMetric.SetW1(w1);
this.verifySemicolon(metricsTokenizer);
break;
case var __case_750_18_0 when global::System.Object.Equals(__case_750_18_0, global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.CharmetricsVv):
float[] vv = new float[2];
vv[0] = this.parseFloat(metricsTokenizer.nextToken());
vv[1] = this.parseFloat(metricsTokenizer.nextToken());
charMetric.SetVv(vv);
this.verifySemicolon(metricsTokenizer);
break;
default:
throw new global::System.IO.IOException(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat("Unknown CharMetrics command '", nextCommand), "'"));
}
}
return charMetric;
}

private void verifySemicolon(global::DripSharp.PdfCarton.Runtime.Fonts.JavaStringTokenizer tokenizer) {
if (tokenizer.hasMoreTokens()) {
string semicolon = tokenizer.nextToken();
if (!(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Equals(";", semicolon))) {
throw new global::System.IO.IOException(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat("Error: Expected semicolon in stream actual='", semicolon), "'"));
}
} else {
throw new global::System.IO.IOException("CharMetrics is missing a semicolon after a command");
}
}

private bool readBoolean() {
return global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.ParseBoolean(this.readString());
}

private int readInt() {
return this.parseInt(this.readString(), 10);
}

private int parseInt(string intValue) {
return this.parseInt(intValue, 10);
}

private int parseInt(string intValue, int radix) {
try {
return global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.ParseInt(intValue, radix);
} catch (global::DripSharp.PdfCarton.Runtime.Fonts.JavaNumberFormatException e) {
throw new global::System.IO.IOException(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat("Error parsing AFM document:", e), e);
}
}

private float readFloat() {
return this.parseFloat(this.readString());
}

private float parseFloat(string floatValue) {
try {
return global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.ParseFloat(floatValue);
} catch (global::DripSharp.PdfCarton.Runtime.Fonts.JavaNumberFormatException e) {
throw new global::System.IO.IOException(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat("Error parsing AFM document:", e), e);
}
}

private string readLine() {
global::System.Text.StringBuilder buf = new global::System.Text.StringBuilder(60);
int nextByte = global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.InputStreamRead(this.input);
while (global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.isWhitespace(nextByte)) {
nextByte = global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.InputStreamRead(this.input);
}
buf.Append(unchecked((char)((char)(nextByte))));
nextByte = global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.InputStreamRead(this.input);
while (((nextByte != -1) && !(global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.isEOL(nextByte)))) {
buf.Append(unchecked((char)((char)(nextByte))));
nextByte = global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.InputStreamRead(this.input);
}
return buf.ToString();
}

private string readString() {
global::System.Text.StringBuilder buf = new global::System.Text.StringBuilder(24);
int nextByte = global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.InputStreamRead(this.input);
while (global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.isWhitespace(nextByte)) {
nextByte = global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.InputStreamRead(this.input);
}
buf.Append(unchecked((char)((char)(nextByte))));
nextByte = global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.InputStreamRead(this.input);
while (((nextByte != -1) && !(global::DripSharp.PdfCarton.Fonts.Afm.AFMParser.isWhitespace(nextByte)))) {
buf.Append(unchecked((char)((char)(nextByte))));
nextByte = global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.InputStreamRead(this.input);
}
return buf.ToString();
}

private void readCommand(string expectedCommand) {
string command = this.readString();
if (!(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Equals(expectedCommand, command))) {
throw new global::System.IO.IOException(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat("Error: Expected '", expectedCommand), "' actual '"), command), "'"));
}
}

private static bool isEOL(int character) {
return ((character == 13) || (character == 10));
}

private static bool isWhitespace(int character) {
switch (character) {
case var __case_942_14_0 when __case_942_14_0 == ' ':
case var __case_943_14_0 when __case_943_14_0 == '\t':
case var __case_944_14_0 when __case_944_14_0 == 13:
case var __case_945_14_0 when __case_945_14_0 == 10:
return true;
default:
return false;
}
}
}
