// <auto-generated />
// Mechanically translated from: org/apache/fontbox/afm/FontMetrics.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Fonts.Afm;

public class FontMetrics {
private float afmVersion;

private int metricSets = 0;

private string fontName = null!;

private string fullName = null!;

private string familyName = null!;

private string weight = null!;

private global::DripSharp.PdfCarton.Fonts.Util.BoundingBox fontBBox = null!;

private string fontVersion = null!;

private string notice = null!;

private string encodingScheme = null!;

private int mappingScheme = 0;

private int escChar = 0;

private string characterSet = null!;

private int characters = 0;

private bool isBaseFont = true;

private float[] vVector = null!;

private bool? isFixedV = default!;

private float capHeight;

private float xHeight;

private float ascender;

private float descender;

private readonly global::System.Collections.Generic.IList<string> comments = new global::System.Collections.Generic.List<string>();

private float underlinePosition;

private float underlineThickness;

private float italicAngle;

private float[] charWidth = null!;

private bool isFixedPitch;

private float standardHorizontalWidth;

private float standardVerticalWidth;

private readonly global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Fonts.Afm.CharMetric> charMetrics = new global::System.Collections.Generic.List<global::DripSharp.PdfCarton.Fonts.Afm.CharMetric>();

private readonly global::System.Collections.Generic.IDictionary<string, global::DripSharp.PdfCarton.Fonts.Afm.CharMetric> charMetricsMap = global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.NewJavaDictionary<string, global::DripSharp.PdfCarton.Fonts.Afm.CharMetric>();

private readonly global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Fonts.Afm.TrackKern> trackKern = new global::System.Collections.Generic.List<global::DripSharp.PdfCarton.Fonts.Afm.TrackKern>();

private readonly global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Fonts.Afm.Composite> composites = new global::System.Collections.Generic.List<global::DripSharp.PdfCarton.Fonts.Afm.Composite>();

private readonly global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Fonts.Afm.KernPair> kernPairs = new global::System.Collections.Generic.List<global::DripSharp.PdfCarton.Fonts.Afm.KernPair>();

private readonly global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Fonts.Afm.KernPair> kernPairs0 = new global::System.Collections.Generic.List<global::DripSharp.PdfCarton.Fonts.Afm.KernPair>();

private readonly global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Fonts.Afm.KernPair> kernPairs1 = new global::System.Collections.Generic.List<global::DripSharp.PdfCarton.Fonts.Afm.KernPair>();

public FontMetrics() {}

public virtual float GetCharacterWidth(string name) {
float result = 0;
global::DripSharp.PdfCarton.Fonts.Afm.CharMetric metric = global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.MapGet(this.charMetricsMap, name);
if ((metric != default!)) {
result = metric.GetWx();
}
return result;
}

public virtual float GetCharacterHeight(string name) {
float result = 0;
global::DripSharp.PdfCarton.Fonts.Afm.CharMetric metric = global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.MapGet(this.charMetricsMap, name);
if ((metric != default!)) {
result = metric.GetWy();
if ((global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.CompareFloat(result, (float)(0)) == 0)) {
result = metric.GetBoundingBox().GetHeight();
}
}
return result;
}

public virtual float GetAverageCharacterWidth() {
float average = 0;
float totalWidths = 0;
float characterCount = 0;
foreach (global::DripSharp.PdfCarton.Fonts.Afm.CharMetric metric in this.charMetrics) {
if ((metric.GetWx() > 0)) {
totalWidths += metric.GetWx();
characterCount += 1;
}
}
if ((totalWidths > 0)) {
average = ((float)(totalWidths) / (float)(characterCount));
}
return average;
}

public virtual void AddComment(string comment) {
global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Add(this.comments, comment);
}

public virtual global::System.Collections.Generic.IList<string> GetComments() {
return global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.UnmodifiableList(this.comments);
}

public virtual float GetAFMVersion() {
return this.afmVersion;
}

public virtual int GetMetricSets() {
return this.metricSets;
}

public virtual void SetAFMVersion(float afmVersionValue) {
this.afmVersion = afmVersionValue;
}

public virtual void SetMetricSets(int metricSetsValue) {
if (((metricSetsValue < 0) || (metricSetsValue > 2))) {
throw new global::System.ArgumentException(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat(global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Concat("The metricSets attribute must be in the ", "set {0,1,2} and not '"), metricSetsValue), "'"));
}
this.metricSets = metricSetsValue;
}

public virtual string GetFontName() {
return this.fontName;
}

public virtual void SetFontName(string name) {
this.fontName = name;
}

public virtual string GetFullName() {
return this.fullName;
}

public virtual void SetFullName(string fullNameValue) {
this.fullName = fullNameValue;
}

public virtual string GetFamilyName() {
return this.familyName;
}

public virtual void SetFamilyName(string familyNameValue) {
this.familyName = familyNameValue;
}

public virtual string GetWeight() {
return this.weight;
}

public virtual void SetWeight(string weightValue) {
this.weight = weightValue;
}

public virtual global::DripSharp.PdfCarton.Fonts.Util.BoundingBox GetFontBBox() {
return this.fontBBox;
}

public virtual void SetFontBBox(global::DripSharp.PdfCarton.Fonts.Util.BoundingBox bBox) {
this.fontBBox = bBox;
}

public virtual string GetNotice() {
return this.notice;
}

public virtual void SetNotice(string noticeValue) {
this.notice = noticeValue;
}

public virtual string GetEncodingScheme() {
return this.encodingScheme;
}

public virtual void SetEncodingScheme(string encodingSchemeValue) {
this.encodingScheme = encodingSchemeValue;
}

public virtual int GetMappingScheme() {
return this.mappingScheme;
}

public virtual void SetMappingScheme(int mappingSchemeValue) {
this.mappingScheme = mappingSchemeValue;
}

public virtual int GetEscChar() {
return this.escChar;
}

public virtual void SetEscChar(int escCharValue) {
this.escChar = escCharValue;
}

public virtual string GetCharacterSet() {
return this.characterSet;
}

public virtual void SetCharacterSet(string characterSetValue) {
this.characterSet = characterSetValue;
}

public virtual int GetCharacters() {
return this.characters;
}

public virtual void SetCharacters(int charactersValue) {
this.characters = charactersValue;
}

public virtual bool GetIsBaseFont() {
return this.isBaseFont;
}

public virtual void SetIsBaseFont(bool isBaseFontValue) {
this.isBaseFont = isBaseFontValue;
}

public virtual float[] GetVVector() {
return this.vVector;
}

public virtual void SetVVector(float[] vVectorValue) {
this.vVector = vVectorValue;
}

public virtual bool GetIsFixedV() {
return ((this.isFixedV == default!) ? (this.vVector != default!) : global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Unbox(this.isFixedV));
}

public virtual void SetIsFixedV(bool isFixedVValue) {
this.isFixedV = isFixedVValue;
}

public virtual float GetCapHeight() {
return this.capHeight;
}

public virtual void SetCapHeight(float capHeightValue) {
this.capHeight = capHeightValue;
}

public virtual float GetXHeight() {
return this.xHeight;
}

public virtual void SetXHeight(float xHeightValue) {
this.xHeight = xHeightValue;
}

public virtual float GetAscender() {
return this.ascender;
}

public virtual void SetAscender(float ascenderValue) {
this.ascender = ascenderValue;
}

public virtual float GetDescender() {
return this.descender;
}

public virtual void SetDescender(float descenderValue) {
this.descender = descenderValue;
}

public virtual string GetFontVersion() {
return this.fontVersion;
}

public virtual void SetFontVersion(string fontVersionValue) {
this.fontVersion = fontVersionValue;
}

public virtual float GetUnderlinePosition() {
return this.underlinePosition;
}

public virtual void SetUnderlinePosition(float underlinePositionValue) {
this.underlinePosition = underlinePositionValue;
}

public virtual float GetUnderlineThickness() {
return this.underlineThickness;
}

public virtual void SetUnderlineThickness(float underlineThicknessValue) {
this.underlineThickness = underlineThicknessValue;
}

public virtual float GetItalicAngle() {
return this.italicAngle;
}

public virtual void SetItalicAngle(float italicAngleValue) {
this.italicAngle = italicAngleValue;
}

public virtual float[] GetCharWidth() {
return this.charWidth;
}

public virtual void SetCharWidth(float[] charWidthValue) {
this.charWidth = charWidthValue;
}

public virtual bool GetIsFixedPitch() {
return this.isFixedPitch;
}

public virtual void SetFixedPitch(bool isFixedPitchValue) {
this.isFixedPitch = isFixedPitchValue;
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Fonts.Afm.CharMetric> GetCharMetrics() {
return global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.UnmodifiableList(this.charMetrics);
}

public virtual void AddCharMetric(global::DripSharp.PdfCarton.Fonts.Afm.CharMetric metric) {
global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Add(this.charMetrics, metric);
global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.MapPut(this.charMetricsMap, metric.GetName(), metric);
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Fonts.Afm.TrackKern> GetTrackKern() {
return global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.UnmodifiableList(this.trackKern);
}

public virtual void AddTrackKern(global::DripSharp.PdfCarton.Fonts.Afm.TrackKern kern) {
global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Add(this.trackKern, kern);
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Fonts.Afm.Composite> GetComposites() {
return global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.UnmodifiableList(this.composites);
}

public virtual void AddComposite(global::DripSharp.PdfCarton.Fonts.Afm.Composite composite) {
global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Add(this.composites, composite);
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Fonts.Afm.KernPair> GetKernPairs() {
return global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.UnmodifiableList(this.kernPairs);
}

public virtual void AddKernPair(global::DripSharp.PdfCarton.Fonts.Afm.KernPair kernPair) {
global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Add(this.kernPairs, kernPair);
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Fonts.Afm.KernPair> GetKernPairs0() {
return global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.UnmodifiableList(this.kernPairs0);
}

public virtual void AddKernPair0(global::DripSharp.PdfCarton.Fonts.Afm.KernPair kernPair) {
global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Add(this.kernPairs0, kernPair);
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Fonts.Afm.KernPair> GetKernPairs1() {
return global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.UnmodifiableList(this.kernPairs1);
}

public virtual void AddKernPair1(global::DripSharp.PdfCarton.Fonts.Afm.KernPair kernPair) {
global::DripSharp.PdfCarton.Runtime.Fonts.JavaCompat.Add(this.kernPairs1, kernPair);
}

public virtual float GetStandardHorizontalWidth() {
return this.standardHorizontalWidth;
}

public virtual void SetStandardHorizontalWidth(float standardHorizontalWidthValue) {
this.standardHorizontalWidth = standardHorizontalWidthValue;
}

public virtual float GetStandardVerticalWidth() {
return this.standardVerticalWidth;
}

public virtual void SetStandardVerticalWidth(float standardVerticalWidthValue) {
this.standardVerticalWidth = standardVerticalWidthValue;
}
}
