// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/pdmodel/graphics/image/PDImage.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Pdmodel.Graphics.Image;

public interface PDImage : global::DripSharp.PdfCarton.Pdmodel.Common.COSObjectable {
public global::SkiaSharp.SKBitmap GetImage();

public global::DripSharp.Runtime.JavaRaster GetRawRaster();

public global::SkiaSharp.SKBitmap GetRawImage();

public global::SkiaSharp.SKBitmap GetImage(global::SkiaSharp.SKRectI region, int subsampling);

public global::SkiaSharp.SKBitmap GetStencilImage(global::DripSharp.Runtime.JavaPaint paint);

public global::System.IO.Stream CreateInputStream();

public global::System.IO.Stream CreateInputStream(global::System.Collections.Generic.IList<string> stopFilters);

public global::System.IO.Stream CreateInputStream(global::DripSharp.PdfCarton.Filter.DecodeOptions options);

public bool IsEmpty();

public bool IsStencil();

public void SetStencil(bool isStencil);

public int GetBitsPerComponent();

public void SetBitsPerComponent(int bitsPerComponent);

public global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDColorSpace GetColorSpace();

public void SetColorSpace(global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDColorSpace colorSpace);

public int GetHeight();

public void SetHeight(int height);

public int GetWidth();

public void SetWidth(int width);

public void SetDecode(global::DripSharp.PdfCarton.Cos.COSArray decode);

public global::DripSharp.PdfCarton.Cos.COSArray GetDecode();

public bool GetInterpolate();

public void SetInterpolate(bool value);

public string GetSuffix();

public new global::DripSharp.PdfCarton.Cos.COSDictionary GetCOSObject();

global::DripSharp.PdfCarton.Cos.COSBase global::DripSharp.PdfCarton.Pdmodel.Common.COSObjectable.GetCOSObject() => (this.GetCOSObject());
}
