// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/pdmodel/interactive/action/PDActionGoTo.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Pdmodel.Interactive.Action;

public class PDActionGoTo : global::DripSharp.PdfCarton.Pdmodel.Interactive.Action.PDAction {
public const string SubType = "GoTo";

public PDActionGoTo() {
this.SetSubType(global::DripSharp.PdfCarton.Pdmodel.Interactive.Action.PDActionGoTo.SubType);
}

public PDActionGoTo(global::DripSharp.PdfCarton.Cos.COSDictionary a) : base(a) {

}

public virtual global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDDestination GetDestination() {
return global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDDestination.Create(this.GetCOSObject().GetDictionaryObject(global::DripSharp.PdfCarton.Cos.COSName.D));
}

public virtual void SetDestination(global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDDestination d) {
if ((d is global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageDestination)) {
global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageDestination pageDest = (global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageDestination)(d!);
global::DripSharp.PdfCarton.Cos.COSArray destArray = pageDest.GetCOSObject();
if ((destArray.Size() >= 1)) {
global::DripSharp.PdfCarton.Cos.COSBase page = destArray.GetObject(0);
if (!((page is global::DripSharp.PdfCarton.Cos.COSDictionary))) {
throw new global::System.ArgumentException("Destination of a GoTo action must be a page dictionary object");
}
}
}
this.GetCOSObject().SetItem(global::DripSharp.PdfCarton.Cos.COSName.D, d);
}
}
