// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/pdmodel/interactive/action/PDActionURI.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Pdmodel.Interactive.Action;

public class PDActionURI : global::DripSharp.PdfCarton.Pdmodel.Interactive.Action.PDAction {
  public const string SubType = "URI";

  public PDActionURI() {
    this.SetSubType(global::DripSharp.PdfCarton.Pdmodel.Interactive.Action.PDActionURI.SubType);
  }

  public PDActionURI(global::DripSharp.PdfCarton.Cos.COSDictionary a) : base(a) {

  }

  public virtual string GetURI() {
    global::DripSharp.PdfCarton.Cos.COSBase @base
      = base.Action.GetDictionaryObject(global::DripSharp.PdfCarton.Cos.COSName.Uri);
    if ((@base is global::DripSharp.PdfCarton.Cos.COSString)) {
      sbyte[] bytes = ((global::DripSharp.PdfCarton.Cos.COSString)(@base!)).GetBytes();
      if ((bytes.Length >= 2)) {
        if ((((bytes[0] & 255) == 254) && ((bytes[1] & 255) == 255))) {
          return base.Action.GetString(global::DripSharp.PdfCarton.Cos.COSName.Uri);
        }
        if ((((bytes[0] & 255) == 255) && ((bytes[1] & 255) == 254))) {
          return base.Action.GetString(global::DripSharp.PdfCarton.Cos.COSName.Uri);
        }
      }
      return global::DripSharp.Runtime.JavaCompat.NewString(bytes,
        global::DripSharp.Runtime.JavaStandardCharsets.UTF8);
    }
    return default!;
  }

  public virtual void SetURI(string uri) {
    base.Action.SetString(global::DripSharp.PdfCarton.Cos.COSName.Uri, uri);
  }

  public virtual bool ShouldTrackMousePosition() {
    return this.Action.GetBoolean("IsMap", false);
  }

  public virtual void SetTrackMousePosition(bool value) {
    this.Action.SetBoolean("IsMap", value);
  }
}
