// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/preflight/graphic/DeviceColorSpaceHelper.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Preflight.Graphic;

public class DeviceColorSpaceHelper
: global::DripSharp.PdfCarton.Preflight.Graphic.StandardColorSpaceHelper {
  public DeviceColorSpaceHelper(global::DripSharp.PdfCarton.Preflight.PreflightContext _context,
    global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDColorSpace _cs) : base(_context, _cs) {

  }

  protected internal override void ProcessPatternColorSpace(global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDColorSpace colorSpace) {
    base.Context.AddValidationError(new global::DripSharp.PdfCarton.Preflight.ValidationResult.ValidationError(global::DripSharp.PdfCarton.Preflight.PreflightConstants.ErrorGraphicInvalidColorSpaceForbidden,
      "Pattern ColorSpace is forbidden"));
  }

  protected internal override void ProcessDeviceNColorSpace(global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDColorSpace colorSpace) {
    base.Context.AddValidationError(new global::DripSharp.PdfCarton.Preflight.ValidationResult.ValidationError(global::DripSharp.PdfCarton.Preflight.PreflightConstants.ErrorGraphicInvalidColorSpaceForbidden,
      "DeviceN ColorSpace is forbidden"));
  }

  protected internal override void ProcessIndexedColorSpace(global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDColorSpace colorSpace) {
    global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDIndexed indexed
      = (global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDIndexed)(colorSpace!);
    global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDColorSpace baseColorSpace
      = indexed.GetBaseColorSpace();
    global::DripSharp.PdfCarton.Preflight.Graphic.ColorSpaces colorSpaces
      = global::DripSharp.PdfCarton.Preflight.Graphic.ColorSpaces.valueOf(baseColorSpace.GetName());
    switch (global::DripSharp.Runtime.JavaCompat.EnumOrdinal(colorSpaces)) {
      case 4:
      case 5:
      case 6:
        base.Context.AddValidationError(new global::DripSharp.PdfCarton.Preflight.ValidationResult.ValidationError(global::DripSharp.PdfCarton.Preflight.PreflightConstants.ErrorGraphicInvalidColorSpaceForbidden,
          global::DripSharp.Runtime.JavaCompat.Concat(colorSpaces.GetLabel(),
          " ColorSpace is forbidden")));
        break;
      default:
        this.ProcessAllColorSpace(baseColorSpace);
        break;
    }
  }
}
