// SPDX-FileCopyrightText: Apache PDFBox contributors
// SPDX-License-Identifier: Apache-2.0

#nullable disable
namespace DripSharp.PdfCarton.Pdmodel.Interactive.Annotation;

public class AppearanceGenerationTest {
private const float DELTA = 0.003F;

private global::DripSharp.PdfCarton.Pdmodel.PDDocument document = null!;

private static readonly global::System.IO.FileInfo IN_DIR = global::DripSharp.PdfCarton.Tests.Support.TestFile(global::DripSharp.PdfCarton.Tests.Support.TestPath("pdfbox", "src/test/resources/org/apache/pdfbox/pdmodel/interactive/annotation"));

private static readonly global::System.IO.FileInfo OUT_DIR = global::DripSharp.PdfCarton.Tests.Support.TestFile(global::DripSharp.PdfCarton.Tests.Support.TestPath("pdfbox", "target/test-output/pdmodel/interactive/annotation"));

private const string NAME_OF_PDF = "AnnotationTypes.pdf";

internal virtual void setUp() {
this.document = global::DripSharp.PdfCarton.Loader.LoadPDF(new global::System.IO.FileInfo(global::System.IO.Path.Combine((global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.AppearanceGenerationTest.IN_DIR).FullName, global::DripSharp.PdfCarton.Tests.Support.TestPath("pdfbox", global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.AppearanceGenerationTest.NAME_OF_PDF))));
global::DripSharp.PdfCarton.Tests.Support.Mkdirs(global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.AppearanceGenerationTest.OUT_DIR);
}

internal virtual void rectangleFullStrokeNoFill() {
global::DripSharp.PdfCarton.Pdmodel.PDPage page = this.document.GetPage(0);
global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.PDAnnotation annotation = global::DripSharp.Runtime.JavaCompat.ListGet(page.GetAnnotations(), 0);
global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.PDAppearanceStream appearanceContentStream = annotation.GetNormalAppearanceStream();
global::DripSharp.PdfCarton.Pdfparser.PDFStreamParser streamParser = new global::DripSharp.PdfCarton.Pdfparser.PDFStreamParser(appearanceContentStream);
global::System.Collections.Generic.IList<object> tokensForOriginal = streamParser.Parse();
annotation.GetCOSObject().RemoveItem(global::DripSharp.PdfCarton.Cos.COSName.Ap);
annotation.ConstructAppearances();
appearanceContentStream = annotation.GetNormalAppearanceStream();
streamParser = new global::DripSharp.PdfCarton.Pdfparser.PDFStreamParser(appearanceContentStream);
global::System.Collections.Generic.IList<object> tokensForPdfbox = streamParser.Parse();
global::DripSharp.Testing.JavaAssertions.Equal(global::DripSharp.Runtime.JavaCompat.CollectionCount(tokensForOriginal), global::DripSharp.Runtime.JavaCompat.CollectionCount(tokensForPdfbox), global::DripSharp.PdfCarton.Tests.Support.TestPath("pdfbox", "The number of tokens in the content stream should be the same"));
int actualToken = 0;
foreach (object tokenForOriginal in tokensForOriginal) {
object tokenForPdfbox = global::DripSharp.Runtime.JavaCompat.ListGet(tokensForPdfbox, actualToken);
global::DripSharp.Testing.JavaAssertions.Equal(global::DripSharp.Runtime.JavaCompat.ClassName(((object)(tokenForOriginal)).GetType(), "DripSharp.PdfCarton", "org.apache.pdfbox"), global::DripSharp.Runtime.JavaCompat.ClassName(((object)(tokenForPdfbox)).GetType(), "DripSharp.PdfCarton", "org.apache.pdfbox"), global::DripSharp.PdfCarton.Tests.Support.TestPath("pdfbox", "The tokens should have the same type"));
if ((tokenForOriginal is global::DripSharp.PdfCarton.Contentstream.@Operator.Operator)) {
global::DripSharp.Testing.JavaAssertions.Equal(((global::DripSharp.PdfCarton.Contentstream.@Operator.Operator)(tokenForOriginal!)).GetName(), ((global::DripSharp.PdfCarton.Contentstream.@Operator.Operator)(tokenForPdfbox!)).GetName(), global::DripSharp.PdfCarton.Tests.Support.TestPath("pdfbox", "The operator generated by PDFBox should be the same Operator"));
} else {
if ((tokenForOriginal is global::DripSharp.PdfCarton.Cos.COSFloat)) {
global::DripSharp.Testing.JavaAssertions.True((global::System.Math.Abs((((global::DripSharp.PdfCarton.Cos.COSFloat)(tokenForOriginal!)).FloatValue() - ((global::DripSharp.PdfCarton.Cos.COSFloat)(tokenForPdfbox!)).FloatValue())) < global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.AppearanceGenerationTest.DELTA), global::DripSharp.PdfCarton.Tests.Support.TestPath("pdfbox", global::DripSharp.Runtime.JavaCompat.Concat("The difference between the numbers should be smaller than ", global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.AppearanceGenerationTest.DELTA)));
}
}
actualToken++;
}
global::System.IO.FileInfo file = new global::System.IO.FileInfo(global::System.IO.Path.Combine((global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.AppearanceGenerationTest.OUT_DIR).FullName, global::DripSharp.PdfCarton.Tests.Support.TestPath("pdfbox", global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.AppearanceGenerationTest.NAME_OF_PDF, "-newAP.pdf"))));
this.document.Save(file);
}

internal virtual void renderTest() {
global::System.IO.FileInfo file = new global::System.IO.FileInfo(global::System.IO.Path.Combine((global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.AppearanceGenerationTest.OUT_DIR).FullName, global::DripSharp.PdfCarton.Tests.Support.TestPath("pdfbox", global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.AppearanceGenerationTest.NAME_OF_PDF)));
this.document.Save(file);
if (!(global::DripSharp.PdfCarton.Rendering.TestPDFToImage.DoTestFile(file, global::DripSharp.PdfCarton.Tests.Support.TestPath("pdfbox", global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.AppearanceGenerationTest.IN_DIR.FullName), global::DripSharp.PdfCarton.Tests.Support.TestPath("pdfbox", global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.AppearanceGenerationTest.OUT_DIR.FullName)))) {
global::DripSharp.Runtime.JavaCompat.@out.WriteLine(global::DripSharp.PdfCarton.Tests.Support.TestPath("pdfbox", global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("Rendering of ", file), " failed or is not identical to expected rendering in "), global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.AppearanceGenerationTest.IN_DIR), " directory")));
}
}

internal virtual void testTinyHorizontalFieldWith0FontSize() {
using (global::DripSharp.PdfCarton.Pdmodel.PDDocument document = new global::DripSharp.PdfCarton.Pdmodel.PDDocument()) {
global::DripSharp.PdfCarton.Pdmodel.PDPage page = new global::DripSharp.PdfCarton.Pdmodel.PDPage(global::DripSharp.PdfCarton.Pdmodel.Common.PDRectangle.A4);
document.AddPage(page);
global::DripSharp.PdfCarton.Pdmodel.Font.PDFont font = new global::DripSharp.PdfCarton.Pdmodel.Font.PDType1Font(global::DripSharp.PdfCarton.Pdmodel.Font.Standard14Fonts.FontName.Helvetica);
global::DripSharp.PdfCarton.Pdmodel.PDResources resources = new global::DripSharp.PdfCarton.Pdmodel.PDResources();
resources.Put(global::DripSharp.PdfCarton.Cos.COSName.Helv, font);
global::DripSharp.PdfCarton.Pdmodel.Interactive.Form.PDAcroForm acroForm = new global::DripSharp.PdfCarton.Pdmodel.Interactive.Form.PDAcroForm(document);
document.GetDocumentCatalog().SetAcroForm(acroForm);
acroForm.SetDefaultResources(resources);
string defaultAppearanceString = "/Helv 0 Tf 0 g";
acroForm.SetDefaultAppearance(global::DripSharp.PdfCarton.Tests.Support.TestPath("pdfbox", defaultAppearanceString));
global::DripSharp.PdfCarton.Pdmodel.Interactive.Form.PDTextField textBox = new global::DripSharp.PdfCarton.Pdmodel.Interactive.Form.PDTextField(acroForm);
textBox.SetPartialName(global::DripSharp.PdfCarton.Tests.Support.TestPath("pdfbox", "SampleField"));
textBox.SetDefaultAppearance(global::DripSharp.PdfCarton.Tests.Support.TestPath("pdfbox", defaultAppearanceString));
global::DripSharp.Runtime.JavaCompat.Add(acroForm.GetFields(), textBox);
global::DripSharp.PdfCarton.Pdmodel.Interactive.Annotation.PDAnnotationWidget widget = global::DripSharp.Runtime.JavaCompat.ListGet(textBox.GetWidgets(), 0);
global::DripSharp.PdfCarton.Pdmodel.Common.PDRectangle rect = new global::DripSharp.PdfCarton.Pdmodel.Common.PDRectangle((float)(50), (float)(750), (float)(1), (float)(50));
widget.SetRectangle(rect);
widget.SetPage(page);
global::DripSharp.Runtime.JavaCompat.Add(page.GetAnnotations(), widget);
textBox.SetValue(global::DripSharp.PdfCarton.Tests.Support.TestPath("pdfbox", ""));
}
}

internal virtual void tearDown() {
this.document.Dispose();
}

[Xunit.Fact]
public void __Upstream_3278492410_a209327a5eab48ee()
{
        this.setUp();
        try
        {
            this.rectangleFullStrokeNoFill();
        }
        finally
        {
            this.tearDown();
        }
}

[Xunit.Fact]
public void __Upstream_3341565768_e8add650e465fa30()
{
        this.setUp();
        try
        {
            this.renderTest();
        }
        finally
        {
            this.tearDown();
        }
}

[Xunit.Fact]
public void __Upstream_0131565430_0595f4d4b81c696b()
{
        this.setUp();
        try
        {
            this.testTinyHorizontalFieldWith0FontSize();
        }
        finally
        {
            this.tearDown();
        }
}
}
