// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/rendering/GroupGraphics.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Rendering;

internal class GroupGraphics : global::DripSharp.Runtime.PdfCartonGraphics2D {
private readonly global::SkiaSharp.SKBitmap groupImage = null!;

private readonly global::SkiaSharp.SKBitmap groupAlphaImage = null!;

private readonly global::DripSharp.Runtime.PdfCartonGraphics2D groupG2D = null!;

private readonly global::DripSharp.Runtime.PdfCartonGraphics2D alphaG2D = null!;

internal GroupGraphics(global::SkiaSharp.SKBitmap groupImage, global::DripSharp.Runtime.PdfCartonGraphics2D groupGraphics) {
this.groupImage = groupImage;
this.groupG2D = groupGraphics;
this.groupAlphaImage = global::DripSharp.Runtime.PdfCartonFontCompat.CreateBitmap(groupImage.Width, groupImage.Height, global::DripSharp.Runtime.PdfCartonFontCompat.TYPE_INT_ARGB);
this.alphaG2D = global::DripSharp.Runtime.PdfCartonFontCompat.CreateGraphics(this.groupAlphaImage);
}

private GroupGraphics(global::SkiaSharp.SKBitmap groupImage, global::DripSharp.Runtime.PdfCartonGraphics2D groupGraphics, global::SkiaSharp.SKBitmap groupAlphaImage, global::DripSharp.Runtime.PdfCartonGraphics2D alphaGraphics) {
this.groupImage = groupImage;
this.groupG2D = groupGraphics;
this.groupAlphaImage = groupAlphaImage;
this.alphaG2D = alphaGraphics;
}

public override void ClearRect(int x, int y, int width, int height) {
this.groupG2D.ClearRect(x, y, width, height);
this.alphaG2D.ClearRect(x, y, width, height);
}

public override void ClipRect(int x, int y, int width, int height) {
this.groupG2D.ClipRect(x, y, width, height);
this.alphaG2D.ClipRect(x, y, width, height);
}

public override void CopyArea(int x, int y, int width, int height, int dx, int dy) {
this.groupG2D.CopyArea(x, y, width, height, dx, dy);
this.alphaG2D.CopyArea(x, y, width, height, dx, dy);
}

public override global::DripSharp.Runtime.PdfCartonGraphics2D Create() {
global::DripSharp.Runtime.PdfCartonGraphics2D g = this.groupG2D.Create();
global::DripSharp.Runtime.PdfCartonGraphics2D a = this.alphaG2D.Create();
if (((g is global::DripSharp.Runtime.PdfCartonGraphics2D) && (a is global::DripSharp.Runtime.PdfCartonGraphics2D))) {
return new global::DripSharp.PdfCarton.Rendering.GroupGraphics(this.groupImage, (global::DripSharp.Runtime.PdfCartonGraphics2D)(g!), this.groupAlphaImage, (global::DripSharp.Runtime.PdfCartonGraphics2D)(a!));
}
g.Dispose();
a.Dispose();
throw new global::System.NotSupportedException("Only Graphics2D supported by this method");
}

public override void Dispose() {
this.groupG2D.Dispose();
this.alphaG2D.Dispose();
}

public override void DrawArc(int x, int y, int width, int height, int startAngle, int arcAngle) {
this.groupG2D.DrawArc(x, y, width, height, startAngle, arcAngle);
this.alphaG2D.DrawArc(x, y, width, height, startAngle, arcAngle);
}

public override bool DrawImage(global::SkiaSharp.SKBitmap img, int x, int y, global::DripSharp.Runtime.JavaColor bgcolor, object observer) {
this.groupG2D.DrawImage(img, x, y, bgcolor, observer);
return this.alphaG2D.DrawImage(img, x, y, bgcolor, observer);
}

public override bool DrawImage(global::SkiaSharp.SKBitmap img, int x, int y, object observer) {
this.groupG2D.DrawImage(img, x, y, observer);
return this.alphaG2D.DrawImage(img, x, y, observer);
}

public override bool DrawImage(global::SkiaSharp.SKBitmap img, int x, int y, int width, int height, global::DripSharp.Runtime.JavaColor bgcolor, object observer) {
this.groupG2D.DrawImage(img, x, y, width, height, bgcolor, observer);
return this.alphaG2D.DrawImage(img, x, y, width, height, bgcolor, observer);
}

public override bool DrawImage(global::SkiaSharp.SKBitmap img, int x, int y, int width, int height, object observer) {
this.groupG2D.DrawImage(img, x, y, width, height, observer);
return this.alphaG2D.DrawImage(img, x, y, width, height, observer);
}

public override bool DrawImage(global::SkiaSharp.SKBitmap img, int dx1, int dy1, int dx2, int dy2, int sx1, int sy1, int sx2, int sy2, global::DripSharp.Runtime.JavaColor bgcolor, object observer) {
this.groupG2D.DrawImage(img, dx1, dy1, dx2, dy2, sx1, sy1, sx2, sy2, bgcolor, observer);
return this.alphaG2D.DrawImage(img, dx1, dy1, dx2, dy2, sx1, sy1, sx2, sy2, bgcolor, observer);
}

public override bool DrawImage(global::SkiaSharp.SKBitmap img, int dx1, int dy1, int dx2, int dy2, int sx1, int sy1, int sx2, int sy2, object observer) {
this.groupG2D.DrawImage(img, dx1, dy1, dx2, dy2, sx1, sy1, sx2, sy2, observer);
return this.alphaG2D.DrawImage(img, dx1, dy1, dx2, dy2, sx1, sy1, sx2, sy2, observer);
}

public override void DrawLine(int x1, int y1, int x2, int y2) {
this.groupG2D.DrawLine(x1, y1, x2, y2);
this.alphaG2D.DrawLine(x1, y1, x2, y2);
}

public override void DrawOval(int x, int y, int width, int height) {
this.groupG2D.DrawOval(x, y, width, height);
this.alphaG2D.DrawOval(x, y, width, height);
}

public override void DrawPolygon(int[] xPoints, int[] yPoints, int nPoints) {
this.groupG2D.DrawPolygon(xPoints, yPoints, nPoints);
this.alphaG2D.DrawPolygon(xPoints, yPoints, nPoints);
}

public override void DrawPolyline(int[] xPoints, int[] yPoints, int nPoints) {
this.groupG2D.DrawPolyline(xPoints, yPoints, nPoints);
this.alphaG2D.DrawPolyline(xPoints, yPoints, nPoints);
}

public override void DrawRoundRect(int x, int y, int width, int height, int arcWidth, int arcHeight) {
this.groupG2D.DrawRoundRect(x, y, width, height, arcWidth, arcHeight);
this.alphaG2D.DrawRoundRect(x, y, width, height, arcWidth, arcHeight);
}

public override void DrawString(global::DripSharp.Runtime.JavaAttributedCharacterIterator iterator, int x, int y) {
this.groupG2D.DrawString(iterator, x, y);
this.alphaG2D.DrawString(iterator, x, y);
}

public override void DrawString(string str, int x, int y) {
this.groupG2D.DrawString(str, x, y);
this.alphaG2D.DrawString(str, x, y);
}

public override void FillArc(int x, int y, int width, int height, int startAngle, int arcAngle) {
this.groupG2D.FillArc(x, y, width, height, startAngle, arcAngle);
this.alphaG2D.FillArc(x, y, width, height, startAngle, arcAngle);
}

public override void FillOval(int x, int y, int width, int height) {
this.groupG2D.FillOval(x, y, width, height);
this.alphaG2D.FillOval(x, y, width, height);
}

public override void FillPolygon(int[] xPoints, int[] yPoints, int nPoints) {
this.groupG2D.FillPolygon(xPoints, yPoints, nPoints);
this.alphaG2D.FillPolygon(xPoints, yPoints, nPoints);
}

public override void FillRect(int x, int y, int width, int height) {
this.groupG2D.FillRect(x, y, width, height);
this.alphaG2D.FillRect(x, y, width, height);
}

public override void FillRoundRect(int x, int y, int width, int height, int arcWidth, int arcHeight) {
this.groupG2D.FillRoundRect(x, y, width, height, arcWidth, arcHeight);
this.alphaG2D.FillRoundRect(x, y, width, height, arcWidth, arcHeight);
}

public override object GetClip() {
return this.groupG2D.GetClip();
}

public override global::SkiaSharp.SKRectI GetClipBounds() {
return this.groupG2D.GetClipBounds();
}

public override global::DripSharp.Runtime.JavaColor GetColor() {
return this.groupG2D.GetColor();
}

public override global::DripSharp.Runtime.JavaFont GetFont() {
return this.groupG2D.GetFont();
}

public override global::DripSharp.Runtime.JavaFontMetrics GetFontMetrics(global::DripSharp.Runtime.JavaFont f) {
return this.groupG2D.GetFontMetrics(f);
}

public override void SetClip(int x, int y, int width, int height) {
this.groupG2D.SetClip(x, y, width, height);
this.alphaG2D.SetClip(x, y, width, height);
}

public override void SetClip(object clip) {
this.groupG2D.SetClip(clip);
this.alphaG2D.SetClip(clip);
}

public override void SetColor(global::DripSharp.Runtime.JavaColor c) {
this.groupG2D.SetColor(c);
this.alphaG2D.SetColor(c);
}

public override void SetFont(global::DripSharp.Runtime.JavaFont font) {
this.groupG2D.SetFont(font);
this.alphaG2D.SetFont(font);
}

public override void SetPaintMode() {
this.groupG2D.SetPaintMode();
this.alphaG2D.SetPaintMode();
}

public override void SetXORMode(global::DripSharp.Runtime.JavaColor c1) {
this.groupG2D.SetXorMode(c1);
this.alphaG2D.SetXorMode(c1);
}

public override void Translate(int x, int y) {
this.groupG2D.Translate(x, y);
this.alphaG2D.Translate(x, y);
}

public override void AddRenderingHints(global::System.Collections.Generic.IDictionary<object, object> hints) {
this.groupG2D.AddRenderingHints(global::DripSharp.Runtime.JavaCompat.CastDictionary<object, object>(hints));
this.alphaG2D.AddRenderingHints(global::DripSharp.Runtime.JavaCompat.CastDictionary<object, object>(hints));
}

public override void Clip(object s) {
this.groupG2D.Clip(s);
this.alphaG2D.Clip(s);
}

public override void Draw(object s) {
this.groupG2D.Draw(s);
this.alphaG2D.Draw(s);
}

public override void DrawGlyphVector(global::DripSharp.Runtime.JavaGlyphVector g, float x, float y) {
this.groupG2D.DrawGlyphVector(g, x, y);
this.alphaG2D.DrawGlyphVector(g, x, y);
}

public override void DrawImage(global::SkiaSharp.SKBitmap img, global::DripSharp.Runtime.JavaBufferedImageOperation op, int x, int y) {
this.groupG2D.DrawBufferedImage(img, op, x, y);
this.alphaG2D.DrawBufferedImage(img, op, x, y);
}

public override bool DrawImage(global::SkiaSharp.SKBitmap img, global::SkiaSharp.SKMatrix xform, object obs) {
this.groupG2D.DrawImage(img, xform, obs);
return this.alphaG2D.DrawImage(img, xform, obs);
}

public override void DrawRenderableImage(global::SkiaSharp.SKBitmap img, global::SkiaSharp.SKMatrix xform) {
this.groupG2D.DrawRenderableImage(img, xform);
this.alphaG2D.DrawRenderableImage(img, xform);
}

public override void DrawRenderedImage(global::SkiaSharp.SKBitmap img, global::SkiaSharp.SKMatrix xform) {
this.groupG2D.DrawRenderedImage(img, xform);
this.alphaG2D.DrawRenderedImage(img, xform);
}

public override void DrawString(global::DripSharp.Runtime.JavaAttributedCharacterIterator iterator, float x, float y) {
this.groupG2D.DrawString(iterator, x, y);
this.alphaG2D.DrawString(iterator, x, y);
}

public override void DrawString(string str, float x, float y) {
this.groupG2D.DrawString(str, x, y);
this.alphaG2D.DrawString(str, x, y);
}

public override void Fill(object s) {
this.groupG2D.Fill(s);
this.alphaG2D.Fill(s);
}

public override global::DripSharp.Runtime.JavaColor GetBackground() {
return this.groupG2D.GetBackground();
}

public override global::DripSharp.Runtime.JavaComposite GetComposite() {
return this.groupG2D.GetComposite();
}

public override global::DripSharp.Runtime.JavaGraphicsConfiguration GetDeviceConfiguration() {
return this.groupG2D.GetDeviceConfiguration();
}

public override global::DripSharp.Runtime.JavaFontRenderContext GetFontRenderContext() {
return this.groupG2D.GetFontRenderContext();
}

public override global::DripSharp.Runtime.JavaPaint GetPaint() {
return this.groupG2D.GetPaint();
}

public override object GetRenderingHint(object hintKey) {
return this.groupG2D.GetRenderingHint(hintKey);
}

public override global::DripSharp.Runtime.PdfCartonRenderingHints GetRenderingHints() {
return this.groupG2D.GetRenderingHints();
}

public override global::DripSharp.Runtime.JavaStroke GetStroke() {
return this.groupG2D.GetStroke();
}

public override global::SkiaSharp.SKMatrix GetTransform() {
return this.groupG2D.GetTransform();
}

public override bool Hit(global::SkiaSharp.SKRectI rect, object s, bool onStroke) {
return this.groupG2D.Hit(rect, s, onStroke);
}

public override void Rotate(double theta) {
this.groupG2D.Rotate(theta);
this.alphaG2D.Rotate(theta);
}

public override void Rotate(double theta, double x, double y) {
this.groupG2D.Rotate(theta, x, y);
this.alphaG2D.Rotate(theta, x, y);
}

public override void Scale(double sx, double sy) {
this.groupG2D.Scale(sx, sy);
this.alphaG2D.Scale(sx, sy);
}

public override void SetBackground(global::DripSharp.Runtime.JavaColor color) {
this.groupG2D.SetBackground(color);
this.alphaG2D.SetBackground(color);
}

public override void SetComposite(global::DripSharp.Runtime.JavaComposite comp) {
this.groupG2D.SetComposite(comp);
this.alphaG2D.SetComposite(comp);
}

public override void SetPaint(global::DripSharp.Runtime.JavaPaint paint) {
this.groupG2D.SetPaint(paint);
this.alphaG2D.SetPaint(paint);
}

public override void SetRenderingHint(object hintKey, object hintValue) {
this.groupG2D.SetRenderingHint(hintKey, hintValue);
this.alphaG2D.SetRenderingHint(hintKey, hintValue);
}

public override void SetRenderingHints(global::System.Collections.Generic.IDictionary<object, object> hints) {
this.groupG2D.SetRenderingHints(global::DripSharp.Runtime.JavaCompat.CastDictionary<object, object>(hints));
this.alphaG2D.SetRenderingHints(global::DripSharp.Runtime.JavaCompat.CastDictionary<object, object>(hints));
}

public override void SetStroke(global::DripSharp.Runtime.JavaStroke s) {
this.groupG2D.SetStroke(s);
this.alphaG2D.SetStroke(s);
}

public override void SetTransform(global::SkiaSharp.SKMatrix tx) {
this.groupG2D.SetTransform(tx);
this.alphaG2D.SetTransform(tx);
}

public override void Shear(double shx, double shy) {
this.groupG2D.Shear(shx, shy);
this.alphaG2D.Shear(shx, shy);
}

public override void Transform(global::SkiaSharp.SKMatrix tx) {
this.groupG2D.Transform(tx);
this.alphaG2D.Transform(tx);
}

public override void Translate(double tx, double ty) {
this.groupG2D.Translate(tx, ty);
this.alphaG2D.Translate(tx, ty);
}

internal virtual void removeBackdrop(global::SkiaSharp.SKBitmap backdrop, int offsetX, int offsetY) {
int groupWidth = this.groupImage.Width;
int groupHeight = this.groupImage.Height;
int backdropWidth = backdrop.Width;
int backdropHeight = backdrop.Height;
int groupType = global::DripSharp.Runtime.PdfCartonFontCompat.GetImageType(this.groupImage);
int groupAlphaType = global::DripSharp.Runtime.PdfCartonFontCompat.GetImageType(this.groupAlphaImage);
int backdropType = global::DripSharp.Runtime.PdfCartonFontCompat.GetImageType(backdrop);
global::DripSharp.Runtime.JavaDataBuffer groupDataBuffer = global::DripSharp.Runtime.PdfCartonFontCompat.GetRaster(this.groupImage).GetDataBuffer();
global::DripSharp.Runtime.JavaDataBuffer groupAlphaDataBuffer = global::DripSharp.Runtime.PdfCartonFontCompat.GetRaster(this.groupAlphaImage).GetDataBuffer();
global::DripSharp.Runtime.JavaDataBuffer backdropDataBuffer = global::DripSharp.Runtime.PdfCartonFontCompat.GetRaster(backdrop).GetDataBuffer();
if (((((((groupType == global::DripSharp.Runtime.PdfCartonFontCompat.TYPE_INT_ARGB) && (groupAlphaType == global::DripSharp.Runtime.PdfCartonFontCompat.TYPE_INT_ARGB)) && ((backdropType == global::DripSharp.Runtime.PdfCartonFontCompat.TYPE_INT_ARGB) || (backdropType == global::DripSharp.Runtime.PdfCartonFontCompat.TYPE_INT_RGB))) && (groupDataBuffer is global::DripSharp.Runtime.JavaDataBufferInt)) && (groupAlphaDataBuffer is global::DripSharp.Runtime.JavaDataBufferInt)) && (backdropDataBuffer is global::DripSharp.Runtime.JavaDataBufferInt))) {
int[] groupData = ((global::DripSharp.Runtime.JavaDataBufferInt)(groupDataBuffer!)).GetData();
int[] groupAlphaData = ((global::DripSharp.Runtime.JavaDataBufferInt)(groupAlphaDataBuffer!)).GetData();
int[] backdropData = ((global::DripSharp.Runtime.JavaDataBufferInt)(backdropDataBuffer!)).GetData();
bool backdropHasAlpha = (backdropType == global::DripSharp.Runtime.PdfCartonFontCompat.TYPE_INT_ARGB);
for (int y__627_22 = 0; (y__627_22 < groupHeight); y__627_22++) {
for (int x__629_26 = 0; (x__629_26 < groupWidth); x__629_26++) {
int index = (x__629_26 + (y__627_22 * groupWidth));
int alphagn__634_25 = ((groupAlphaData[index] >> unchecked((int)(24))) & 255);
if ((alphagn__634_25 == 0)) {
groupData[index] = 0;
continue;
}
int backdropX__642_25 = (x__629_26 + offsetX);
int backdropY__643_25 = (y__627_22 + offsetY);
int backdropRGB__644_25;
float alpha0__645_27;
if (((((backdropX__642_25 >= 0) && (backdropX__642_25 < backdropWidth)) && (backdropY__643_25 >= 0)) && (backdropY__643_25 < backdropHeight))) {
backdropRGB__644_25 = backdropData[(backdropX__642_25 + (backdropY__643_25 * backdropWidth))];
alpha0__645_27 = (backdropHasAlpha ? ((backdropRGB__644_25 >> unchecked((int)(24))) & 255) : 255);
} else {
backdropRGB__644_25 = 0;
alpha0__645_27 = 0;
}
float alphaFactor__661_27 = (((float)(alpha0__645_27) / alphagn__634_25) - ((float)(alpha0__645_27) / (float)(255.0F)));
int groupRGB__662_25 = groupData[index];
int r__665_25 = this.backdropRemoval(groupRGB__662_25, backdropRGB__644_25, 16, alphaFactor__661_27);
int g__666_25 = this.backdropRemoval(groupRGB__662_25, backdropRGB__644_25, 8, alphaFactor__661_27);
int b__667_25 = this.backdropRemoval(groupRGB__662_25, backdropRGB__644_25, 0, alphaFactor__661_27);
groupData[index] = ((((alphagn__634_25 << unchecked((int)(24))) | (r__665_25 << unchecked((int)(16)))) | (g__666_25 << unchecked((int)(8)))) | b__667_25);
}
}
} else {
for (int y__679_22 = 0; (y__679_22 < groupHeight); y__679_22++) {
for (int x__681_26 = 0; (x__681_26 < groupWidth); x__681_26++) {
int alphagn__683_25 = ((global::DripSharp.Runtime.PdfCartonFontCompat.GetRgb(this.groupAlphaImage, x__681_26, y__679_22) >> unchecked((int)(24))) & 255);
if ((alphagn__683_25 == 0)) {
global::DripSharp.Runtime.PdfCartonFontCompat.SetRgb(this.groupImage, x__681_26, y__679_22, 0);
continue;
}
int backdropX__690_25 = (x__681_26 + offsetX);
int backdropY__691_25 = (y__679_22 + offsetY);
int backdropRGB__692_25;
float alpha0__693_27;
if (((((backdropX__690_25 >= 0) && (backdropX__690_25 < backdropWidth)) && (backdropY__691_25 >= 0)) && (backdropY__691_25 < backdropHeight))) {
backdropRGB__692_25 = global::DripSharp.Runtime.PdfCartonFontCompat.GetRgb(backdrop, backdropX__690_25, backdropY__691_25);
alpha0__693_27 = ((backdropRGB__692_25 >> unchecked((int)(24))) & 255);
} else {
backdropRGB__692_25 = 0;
alpha0__693_27 = 0;
}
int groupRGB__706_25 = global::DripSharp.Runtime.PdfCartonFontCompat.GetRgb(this.groupImage, x__681_26, y__679_22);
float alphaFactor__707_27 = (((float)(alpha0__693_27) / alphagn__683_25) - ((float)(alpha0__693_27) / (float)(255.0F)));
int r__709_25 = this.backdropRemoval(groupRGB__706_25, backdropRGB__692_25, 16, alphaFactor__707_27);
int g__710_25 = this.backdropRemoval(groupRGB__706_25, backdropRGB__692_25, 8, alphaFactor__707_27);
int b__711_25 = this.backdropRemoval(groupRGB__706_25, backdropRGB__692_25, 0, alphaFactor__707_27);
global::DripSharp.Runtime.PdfCartonFontCompat.SetRgb(this.groupImage, x__681_26, y__679_22, ((((alphagn__683_25 << unchecked((int)(24))) | (r__709_25 << unchecked((int)(16)))) | (g__710_25 << unchecked((int)(8)))) | b__711_25));
}
}
}
}

private int backdropRemoval(int groupRGB, int backdropRGB, int shift, float alphaFactor) {
float cn = ((groupRGB >> unchecked((int)(shift))) & 255);
float c0 = ((backdropRGB >> unchecked((int)(shift))) & 255);
int c = global::DripSharp.Runtime.JavaCompat.MathRoundFloat((cn + ((cn - c0) * alphaFactor)));
return ((c < 0) ? 0 : ((c > 255) ? 255 : c));
}
}
