// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/preflight/process/reflect/ResourcesValidationProcess.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Preflight.Process.Reflect;

public class ResourcesValidationProcess
: global::DripSharp.PdfCarton.Preflight.Process.AbstractProcess {
  public override void Validate(global::DripSharp.PdfCarton.Preflight.PreflightContext ctx) {
    global::DripSharp.PdfCarton.Preflight.PreflightPath vPath = ctx.GetValidationPath();
    if (vPath.IsEmpty()) {} else {
      if (!(vPath.IsExpectedType(typeof(global::DripSharp.PdfCarton.Pdmodel.PDResources)))) {
        this.AddValidationError(ctx,
          new global::DripSharp.PdfCarton.Preflight.ValidationResult.ValidationError(global::DripSharp.PdfCarton.Preflight.PreflightConstants.ErrorPdfProcessingMissing,
          "Resources validation process needs at least one PDResources object"));
      } else {
        global::DripSharp.PdfCarton.Pdmodel.PDResources resources
          = (global::DripSharp.PdfCarton.Pdmodel.PDResources)(vPath.Peek()!);
        this.ValidateFonts(ctx, resources);
        this.ValidateExtGStates(ctx, resources);
        this.ValidateShadingPattern(ctx, resources);
        this.ValidateTilingPattern(ctx, resources);
        this.ValidateXObjects(ctx, resources);
      }
    }
  }

  protected internal virtual void ValidateFonts(global::DripSharp.PdfCarton.Preflight.PreflightContext context,
    global::DripSharp.PdfCarton.Pdmodel.PDResources resources) {
    global::System.Collections.Generic.IDictionary<string,
      global::DripSharp.PdfCarton.Pdmodel.Font.PDFont> mapOfFonts
      = this.getFonts(resources.GetCOSObject(), context);
    foreach (global::DripSharp.Runtime.JavaMapEntry<string,
      global::DripSharp.PdfCarton.Pdmodel.Font.PDFont> entry in global::DripSharp.Runtime.JavaCompat.MapEntrySet(mapOfFonts)) {
      global::DripSharp.PdfCarton.Preflight.Utils.ContextHelper.ValidateElement(context,
        entry.Value, global::DripSharp.PdfCarton.Preflight.PreflightConfiguration.FontProcess);
    }
  }

  private global::System.Collections.Generic.IDictionary<string,
    global::DripSharp.PdfCarton.Pdmodel.Font.PDFont> getFonts(global::DripSharp.PdfCarton.Cos.COSDictionary resources,
    global::DripSharp.PdfCarton.Preflight.PreflightContext context) {
    global::System.Collections.Generic.IDictionary<string,
      global::DripSharp.PdfCarton.Pdmodel.Font.PDFont> fonts
      = global::DripSharp.Runtime.JavaCompat.NewJavaDictionary<string,
      global::DripSharp.PdfCarton.Pdmodel.Font.PDFont>();
    global::DripSharp.PdfCarton.Cos.COSDictionary fontsDictionary
      = (global::DripSharp.PdfCarton.Cos.COSDictionary)(resources.GetDictionaryObject(global::DripSharp.PdfCarton.Cos.COSName.Font)!);
    if ((fontsDictionary == default!)) {
      fontsDictionary = new global::DripSharp.PdfCarton.Cos.COSDictionary();
      resources.SetItem(global::DripSharp.PdfCarton.Cos.COSName.Font, fontsDictionary);
    }
    foreach (global::DripSharp.PdfCarton.Cos.COSName fontName in fontsDictionary.KeySet()) {
      global::DripSharp.PdfCarton.Cos.COSBase font = fontsDictionary.GetDictionaryObject(fontName);
      if ((font is global::DripSharp.PdfCarton.Cos.COSDictionary)) {
        global::DripSharp.PdfCarton.Pdmodel.Font.PDFont newFont = default!;
        try {
          newFont
            = global::DripSharp.PdfCarton.Pdmodel.Font.PDFontFactory.CreateFont((global::DripSharp.PdfCarton.Cos.COSDictionary)(font!));
        } catch (global::System.IO.IOException e) {
          this.AddFontError((global::DripSharp.PdfCarton.Cos.COSDictionary)(font!), context, e);
        }
        if ((newFont! != default!)) {
          global::DripSharp.Runtime.JavaCompat.MapPut(fonts, fontName.GetName(), newFont!);
        }
      }
    }
    return fonts;
  }

  protected internal virtual void ValidateExtGStates(global::DripSharp.PdfCarton.Preflight.PreflightContext context,
    global::DripSharp.PdfCarton.Pdmodel.PDResources resources) {
    global::DripSharp.PdfCarton.Cos.COSDictionary extGState
      = resources.GetCOSObject().GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName.ExtGState);
    if ((extGState != default!)) {
      global::DripSharp.PdfCarton.Preflight.Utils.ContextHelper.ValidateElement(context, extGState,
        global::DripSharp.PdfCarton.Preflight.PreflightConfiguration.ExtgstateProcess);
    }
  }

  protected internal virtual void ValidateShadingPattern(global::DripSharp.PdfCarton.Preflight.PreflightContext context,
    global::DripSharp.PdfCarton.Pdmodel.PDResources resources) {
    try {
      foreach (global::DripSharp.PdfCarton.Cos.COSName name in resources.GetShadingNames()) {
        global::DripSharp.PdfCarton.Pdmodel.Graphics.Shading.PDShading shading
          = resources.GetShading(name);
        global::DripSharp.PdfCarton.Preflight.Utils.ContextHelper.ValidateElement(context, shading,
          global::DripSharp.PdfCarton.Preflight.PreflightConfiguration.ShadingPatternProcess);
      }
    } catch (global::System.IO.IOException e) {
      context.AddValidationError(new global::DripSharp.PdfCarton.Preflight.ValidationResult.ValidationError(global::DripSharp.PdfCarton.Preflight.PreflightConstants.ErrorGraphicInvalidPatternDefinition,
        global::DripSharp.Runtime.JavaCompat.ExceptionMessage(e), e));
    }
  }

  protected internal virtual void ValidateTilingPattern(global::DripSharp.PdfCarton.Preflight.PreflightContext context,
    global::DripSharp.PdfCarton.Pdmodel.PDResources resources) {
    try {
      foreach (global::DripSharp.PdfCarton.Cos.COSName name in resources.GetPatternNames()) {
        global::DripSharp.PdfCarton.Pdmodel.Graphics.Pattern.PDAbstractPattern pattern
          = resources.GetPattern(name);
        if ((pattern is global::DripSharp.PdfCarton.Pdmodel.Graphics.Pattern.PDTilingPattern)) {
          global::DripSharp.PdfCarton.Preflight.Utils.ContextHelper.ValidateElement(context,
            pattern,
            global::DripSharp.PdfCarton.Preflight.PreflightConfiguration.TilingPatternProcess);
        }
      }
    } catch (global::System.IO.IOException e) {
      context.AddValidationError(new global::DripSharp.PdfCarton.Preflight.ValidationResult.ValidationError(global::DripSharp.PdfCarton.Preflight.PreflightConstants.ErrorGraphicInvalidPatternDefinition,
        global::DripSharp.Runtime.JavaCompat.ExceptionMessage(e), e));
    }
  }

  protected internal virtual void ValidateXObjects(global::DripSharp.PdfCarton.Preflight.PreflightContext context,
    global::DripSharp.PdfCarton.Pdmodel.PDResources resources) {
    global::DripSharp.PdfCarton.Cos.COSDictionary mapOfXObj
      = resources.GetCOSObject().GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName.Xobject);
    if ((mapOfXObj == default!)) {
      return;
    }
    foreach (global::DripSharp.Runtime.JavaMapEntry<global::DripSharp.PdfCarton.Cos.COSName,
      global::DripSharp.PdfCarton.Cos.COSBase> entry in mapOfXObj.EntrySet()) {
      global::DripSharp.PdfCarton.Cos.COSBase xobj = entry.Value;
      if ((xobj is global::DripSharp.PdfCarton.Cos.COSObject)) {
        xobj = ((global::DripSharp.PdfCarton.Cos.COSObject)(xobj!)).GetObject();
      }
      if ((xobj is global::DripSharp.PdfCarton.Cos.COSStream)) {
        try {
          global::DripSharp.PdfCarton.Pdmodel.Graphics.PDXObject pdXObject
            = global::DripSharp.PdfCarton.Pdmodel.Graphics.PDXObject.CreateXObject(xobj, resources);
          global::DripSharp.PdfCarton.Preflight.Utils.ContextHelper.ValidateElement(context,
            pdXObject, global::DripSharp.PdfCarton.Preflight.PreflightConfiguration.GraphicProcess);
        } catch (global::System.IO.IOException e) {
          context.AddValidationError(new global::DripSharp.PdfCarton.Preflight.ValidationResult.ValidationError(global::DripSharp.PdfCarton.Preflight.PreflightConstants.ErrorGraphicMain,
            global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.ExceptionMessage(e),
            " for entry '"), entry.Key.GetName()), "'"), e));
        }
      }
    }
  }
}
