// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/pdmodel/interactive/documentnavigation/destination/PDDestination.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination;

public abstract class PDDestination
: global::DripSharp.PdfCarton.Pdmodel.Common.PDDestinationOrAction {
  public static global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDDestination Create(global::DripSharp.PdfCarton.Cos.COSBase @base) {
    global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDDestination retval
      = default!;
    if ((@base == default!)) {} else {
      if ((((@base is global::DripSharp.PdfCarton.Cos.COSArray)
        && (((global::DripSharp.PdfCarton.Cos.COSArray)(@base!)).Size() > 1))
        && (((global::DripSharp.PdfCarton.Cos.COSArray)(@base!)).GetObject(1) is global::DripSharp.PdfCarton.Cos.COSName))) {
        global::DripSharp.PdfCarton.Cos.COSArray array
          = (global::DripSharp.PdfCarton.Cos.COSArray)(@base!);
        global::DripSharp.PdfCarton.Cos.COSName type
          = (global::DripSharp.PdfCarton.Cos.COSName)(array.GetObject(1)!);
        string typeString = type.GetName();
        switch (typeString) {
          case var __case_62_22_0 when global::System.Object.Equals(__case_62_22_0,
              global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageFitDestination.Type):
          case var __case_63_22_0 when global::System.Object.Equals(__case_63_22_0,
              global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageFitDestination.TypeBounded):
            retval
              = new global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageFitDestination(array);
            break;
          case var __case_66_22_0 when global::System.Object.Equals(__case_66_22_0,
              global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageFitHeightDestination.Type):
          case var __case_67_22_0 when global::System.Object.Equals(__case_67_22_0,
              global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageFitHeightDestination.TypeBounded):
            retval
              = new global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageFitHeightDestination(array);
            break;
          case var __case_70_22_0 when global::System.Object.Equals(__case_70_22_0,
              global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageFitRectangleDestination.Type):
            retval
              = new global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageFitRectangleDestination(array);
            break;
          case var __case_73_22_0 when global::System.Object.Equals(__case_73_22_0,
              global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageFitWidthDestination.Type):
          case var __case_74_22_0 when global::System.Object.Equals(__case_74_22_0,
              global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageFitWidthDestination.TypeBounded):
            retval
              = new global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageFitWidthDestination(array);
            break;
          case var __case_77_22_0 when global::System.Object.Equals(__case_77_22_0,
              global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageXYZDestination.Type):
            retval
              = new global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageXYZDestination(array);
            break;
          default:
            throw new global::System.IO.IOException(global::DripSharp.Runtime.JavaCompat.Concat("Unknown destination type: ",
              type.GetName()));
        }
      } else {
        if ((@base is global::DripSharp.PdfCarton.Cos.COSString)) {
          retval
            = new global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDNamedDestination((global::DripSharp.PdfCarton.Cos.COSString)(@base!));
        } else {
          if ((@base is global::DripSharp.PdfCarton.Cos.COSName)) {
            retval
              = new global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDNamedDestination((global::DripSharp.PdfCarton.Cos.COSName)(@base!));
          } else {
            throw new global::System.IO.IOException(global::DripSharp.Runtime.JavaCompat.Concat("Error: can't convert to Destination ",
              @base));
          }
        }
      }
    }
    return retval!;
  }

  public abstract global::DripSharp.PdfCarton.Cos.COSBase GetCOSObject();

  public PDDestination() {}
}
