// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/pdmodel/interactive/pagenavigation/PDTransitionDimension.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Pdmodel.Interactive.Pagenavigation;

public sealed class PDTransitionDimension {
[global::DripSharp.Runtime.JavaEnumNameAttribute("H")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(0)]
public static readonly global::DripSharp.PdfCarton.Pdmodel.Interactive.Pagenavigation.PDTransitionDimension H = new global::DripSharp.PdfCarton.Pdmodel.Interactive.Pagenavigation.PDTransitionDimension();

[global::DripSharp.Runtime.JavaEnumNameAttribute("V")]
[global::DripSharp.Runtime.JavaEnumOrdinalAttribute(1)]
public static readonly global::DripSharp.PdfCarton.Pdmodel.Interactive.Pagenavigation.PDTransitionDimension V = new global::DripSharp.PdfCarton.Pdmodel.Interactive.Pagenavigation.PDTransitionDimension();

private PDTransitionDimension() {}


public static PDTransitionDimension[] values() => global::DripSharp.Runtime.JavaCompat.EnumValues<PDTransitionDimension>();
public static PDTransitionDimension valueOf(string name) => global::DripSharp.Runtime.JavaCompat.EnumValueOf<PDTransitionDimension>(name);

public override string ToString() => global::DripSharp.Runtime.JavaCompat.EnumName(this);
}
