// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/pdmodel/common/function/PDFunctionType2.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Pdmodel.Common.Function;

public class PDFunctionType2 : global::DripSharp.PdfCarton.Pdmodel.Common.Function.PDFunction {
  private readonly global::DripSharp.PdfCarton.Cos.COSArray c0 = null!;

  private readonly global::DripSharp.PdfCarton.Cos.COSArray c1 = null!;

  private readonly float exponent = default;

  public PDFunctionType2(global::DripSharp.PdfCarton.Cos.COSBase function) : base(function) {
    global::DripSharp.PdfCarton.Cos.COSDictionary cosObject = this.GetCOSObject();
    global::DripSharp.PdfCarton.Cos.COSArray cosArray0
      = cosObject.GetCOSArray(global::DripSharp.PdfCarton.Cos.COSName.C0);
    if ((cosArray0 != default!)) {
      this.c0 = cosArray0;
    } else {
      this.c0 = new global::DripSharp.PdfCarton.Cos.COSArray();
    }
    if ((this.c0.Size() == 0)) {
      this.c0.Add(new global::DripSharp.PdfCarton.Cos.COSFloat((float)(0)));
    }
    global::DripSharp.PdfCarton.Cos.COSArray cosArray1
      = cosObject.GetCOSArray(global::DripSharp.PdfCarton.Cos.COSName.C1);
    if ((cosArray1 != default!)) {
      this.c1 = cosArray1;
    } else {
      this.c1 = new global::DripSharp.PdfCarton.Cos.COSArray();
    }
    if ((this.c1.Size() == 0)) {
      this.c1.Add(new global::DripSharp.PdfCarton.Cos.COSFloat((float)(1)));
    }
    this.exponent = this.GetCOSObject().GetFloat(global::DripSharp.PdfCarton.Cos.COSName.N);
  }

  public override int GetFunctionType() {
    return 2;
  }

  public override float[] Eval(float[] input) {
    float xToN = (float)(global::System.Math.Pow((double)(input[0]), (double)(this.exponent)));
    float[] result = new float[global::System.Math.Min(this.c0.Size(), this.c1.Size())];
    for (int j = 0; (j < result.Length); j++) {
      float c0j = ((global::DripSharp.PdfCarton.Cos.COSNumber)(this.c0.Get(j)!)).FloatValue();
      float c1j = ((global::DripSharp.PdfCarton.Cos.COSNumber)(this.c1.Get(j)!)).FloatValue();
      result[j] = (c0j + (xToN * (c1j - c0j)));
    }
    return this.ClipToRange(result);
  }

  public virtual global::DripSharp.PdfCarton.Cos.COSArray GetC0() {
    return this.c0;
  }

  public virtual global::DripSharp.PdfCarton.Cos.COSArray GetC1() {
    return this.c1;
  }

  public virtual float GetN() {
    return this.exponent;
  }

  public override string ToString() {
    return global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("FunctionType2{",
      "C0: "), this.GetC0()), " "), "C1: "), this.GetC1()), " "), "N: "), this.GetN()), "}");
  }
}
