// <auto-generated />
// Mechanically translated from: org/apache/pdfbox/pdmodel/PDDocumentCatalog.java
// Upstream repository: https://github.com/apache/pdfbox.git
// Upstream revision: 9286e47d89d6877005c9d2d0f2fd38793a62519a
// Translator: DripSharp 0.1.0
// IMPORTANT: This mechanically translated derivative has been changed from the upstream source.
// Applicable upstream notices: see NOTICE.txt.
#nullable disable
namespace DripSharp.PdfCarton.Pdmodel;

public class PDDocumentCatalog : global::DripSharp.PdfCarton.Pdmodel.Common.COSObjectable {
private static readonly global::Microsoft.Extensions.Logging.ILogger LOG = global::Microsoft.Extensions.Logging.Abstractions.NullLogger.Instance;

private readonly global::DripSharp.PdfCarton.Cos.COSDictionary root = null!;

private readonly global::DripSharp.PdfCarton.Pdmodel.PDDocument document = null!;

private global::DripSharp.PdfCarton.Pdmodel.Fixup.PDDocumentFixup acroFormFixupApplied = null!;

private global::DripSharp.PdfCarton.Pdmodel.Interactive.Form.PDAcroForm cachedAcroForm = null!;

protected internal PDDocumentCatalog(global::DripSharp.PdfCarton.Pdmodel.PDDocument doc) {
this.document = doc;
this.root = new global::DripSharp.PdfCarton.Cos.COSDictionary();
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.Type, global::DripSharp.PdfCarton.Cos.COSName.Catalog);
this.document.GetDocument().GetTrailer().SetItem(global::DripSharp.PdfCarton.Cos.COSName.Root, this.root);
}

protected internal PDDocumentCatalog(global::DripSharp.PdfCarton.Pdmodel.PDDocument doc, global::DripSharp.PdfCarton.Cos.COSDictionary rootDictionary) {
this.document = doc;
this.root = rootDictionary;
}

public virtual global::DripSharp.PdfCarton.Cos.COSDictionary GetCOSObject() {
return this.root;
}

public virtual global::DripSharp.PdfCarton.Pdmodel.Interactive.Form.PDAcroForm GetAcroForm() {
return this.GetAcroForm(new global::DripSharp.PdfCarton.Pdmodel.Fixup.AcroFormDefaultFixup(this.document));
}

public virtual global::DripSharp.PdfCarton.Pdmodel.Interactive.Form.PDAcroForm GetAcroForm(global::DripSharp.PdfCarton.Pdmodel.Fixup.PDDocumentFixup acroFormFixup) {
if (((acroFormFixup != default!) && (acroFormFixup != this.acroFormFixupApplied))) {
acroFormFixup.Apply();
this.cachedAcroForm = default!;
this.acroFormFixupApplied = acroFormFixup;
} else {
if ((this.acroFormFixupApplied != default!)) {
global::Microsoft.Extensions.Logging.LoggerExtensions.LogDebug(global::DripSharp.PdfCarton.Pdmodel.PDDocumentCatalog.LOG, global::DripSharp.Runtime.JavaCompat.StringValueOf("AcroForm content has already been retrieved with fixes applied - original content changed because of that"));
}
}
if ((this.cachedAcroForm == default!)) {
global::DripSharp.PdfCarton.Cos.COSDictionary dict = this.root.GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName.AcroForm);
this.cachedAcroForm = ((dict == default!) ? (global::DripSharp.PdfCarton.Pdmodel.Interactive.Form.PDAcroForm)(default!) : new global::DripSharp.PdfCarton.Pdmodel.Interactive.Form.PDAcroForm(this.document, dict));
}
return this.cachedAcroForm;
}

public virtual void SetAcroForm(global::DripSharp.PdfCarton.Pdmodel.Interactive.Form.PDAcroForm acroForm) {
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.AcroForm, acroForm);
this.cachedAcroForm = default!;
}

public virtual global::DripSharp.PdfCarton.Pdmodel.PDPageTree GetPages() {
return new global::DripSharp.PdfCarton.Pdmodel.PDPageTree(this.root.GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName.Pages), this.document);
}

public virtual global::DripSharp.PdfCarton.Pdmodel.Interactive.Viewerpreferences.PDViewerPreferences GetViewerPreferences() {
global::DripSharp.PdfCarton.Cos.COSDictionary viewerPref = this.root.GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName.ViewerPreferences);
return ((viewerPref != default!) ? new global::DripSharp.PdfCarton.Pdmodel.Interactive.Viewerpreferences.PDViewerPreferences(viewerPref) : (global::DripSharp.PdfCarton.Pdmodel.Interactive.Viewerpreferences.PDViewerPreferences)(default!));
}

public virtual void SetViewerPreferences(global::DripSharp.PdfCarton.Pdmodel.Interactive.Viewerpreferences.PDViewerPreferences prefs) {
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.ViewerPreferences, prefs);
}

public virtual global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Outline.PDDocumentOutline GetDocumentOutline() {
global::DripSharp.PdfCarton.Cos.COSDictionary outlineDict = this.root.GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName.Outlines);
return ((outlineDict != default!) ? new global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Outline.PDDocumentOutline(outlineDict) : (global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Outline.PDDocumentOutline)(default!));
}

public virtual void SetDocumentOutline(global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Outline.PDDocumentOutline outlines) {
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.Outlines, outlines);
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Pdmodel.Interactive.Pagenavigation.PDThread> GetThreads() {
global::DripSharp.PdfCarton.Cos.COSArray array = this.root.GetCOSArray(global::DripSharp.PdfCarton.Cos.COSName.Threads);
if ((array == default!)) {
array = new global::DripSharp.PdfCarton.Cos.COSArray();
array.SetDirect(false);
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.Threads, array);
}
global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Pdmodel.Interactive.Pagenavigation.PDThread> pdObjects = new global::System.Collections.Generic.List<global::DripSharp.PdfCarton.Pdmodel.Interactive.Pagenavigation.PDThread>(array.Size());
for (int i = 0; (i < array.Size()); i++) {
global::DripSharp.Runtime.JavaCompat.Add(pdObjects, new global::DripSharp.PdfCarton.Pdmodel.Interactive.Pagenavigation.PDThread((global::DripSharp.PdfCarton.Cos.COSDictionary)(array.GetObject(i)!)));
}
return new global::DripSharp.PdfCarton.Pdmodel.Common.COSArrayList<global::DripSharp.PdfCarton.Pdmodel.Interactive.Pagenavigation.PDThread>(pdObjects, array);
}

public virtual void SetThreads(global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Pdmodel.Interactive.Pagenavigation.PDThread> threads) {
if ((threads == default!)) {
this.root.RemoveItem(global::DripSharp.PdfCarton.Cos.COSName.Threads);
return;
}
global::DripSharp.PdfCarton.Cos.COSArray threadsArray = new global::DripSharp.PdfCarton.Cos.COSArray(threads);
threadsArray.SetDirect(false);
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.Threads, threadsArray);
}

public virtual global::DripSharp.PdfCarton.Pdmodel.Common.PDMetadata GetMetadata() {
global::DripSharp.PdfCarton.Cos.COSStream metaObj = this.root.GetCOSStream(global::DripSharp.PdfCarton.Cos.COSName.Metadata);
return ((metaObj != default!) ? new global::DripSharp.PdfCarton.Pdmodel.Common.PDMetadata(metaObj) : (global::DripSharp.PdfCarton.Pdmodel.Common.PDMetadata)(default!));
}

public virtual void SetMetadata(global::DripSharp.PdfCarton.Pdmodel.Common.PDMetadata meta) {
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.Metadata, meta);
}

public virtual void SetOpenAction(global::DripSharp.PdfCarton.Pdmodel.Common.PDDestinationOrAction action) {
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.OpenAction, action);
}

public virtual global::DripSharp.PdfCarton.Pdmodel.Common.PDDestinationOrAction GetOpenAction() {
global::DripSharp.PdfCarton.Cos.COSBase openAction = this.root.GetDictionaryObject(global::DripSharp.PdfCarton.Cos.COSName.OpenAction);
if ((openAction is global::DripSharp.PdfCarton.Cos.COSDictionary)) {
return global::DripSharp.PdfCarton.Pdmodel.Interactive.Action.PDActionFactory.CreateAction((global::DripSharp.PdfCarton.Cos.COSDictionary)(openAction!));
} else {
if ((openAction is global::DripSharp.PdfCarton.Cos.COSArray)) {
return global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDDestination.Create(openAction);
} else {
return default!;
}
}
}

public virtual global::DripSharp.PdfCarton.Pdmodel.Interactive.Action.PDDocumentCatalogAdditionalActions GetActions() {
global::DripSharp.PdfCarton.Cos.COSDictionary addAction = this.root.GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName.Aa);
if ((addAction == default!)) {
addAction = new global::DripSharp.PdfCarton.Cos.COSDictionary();
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.Aa, addAction);
}
return new global::DripSharp.PdfCarton.Pdmodel.Interactive.Action.PDDocumentCatalogAdditionalActions(addAction);
}

public virtual void SetActions(global::DripSharp.PdfCarton.Pdmodel.Interactive.Action.PDDocumentCatalogAdditionalActions actions) {
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.Aa, actions);
}

public virtual global::DripSharp.PdfCarton.Pdmodel.PDDocumentNameDictionary GetNames() {
global::DripSharp.PdfCarton.Cos.COSDictionary names = this.root.GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName.Names);
return ((names == default!) ? (global::DripSharp.PdfCarton.Pdmodel.PDDocumentNameDictionary)(default!) : new global::DripSharp.PdfCarton.Pdmodel.PDDocumentNameDictionary(this, names));
}

public virtual global::DripSharp.PdfCarton.Pdmodel.PDDocumentNameDestinationDictionary GetDests() {
global::DripSharp.PdfCarton.Cos.COSDictionary dests = this.root.GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName.Dests);
return ((dests != default!) ? new global::DripSharp.PdfCarton.Pdmodel.PDDocumentNameDestinationDictionary(dests) : (global::DripSharp.PdfCarton.Pdmodel.PDDocumentNameDestinationDictionary)(default!));
}

public virtual global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageDestination FindNamedDestinationPage(global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDNamedDestination namedDest) {
global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageDestination pageDestination = default!;
global::DripSharp.PdfCarton.Pdmodel.PDDocumentNameDictionary namesDict = this.GetNames();
if ((namesDict != default!)) {
global::DripSharp.PdfCarton.Pdmodel.PDDestinationNameTreeNode destsTree = namesDict.GetDests();
if ((destsTree != default!)) {
pageDestination = destsTree.GetValue(namedDest.GetNamedDestination());
}
}
if ((pageDestination! == default!)) {
global::DripSharp.PdfCarton.Pdmodel.PDDocumentNameDestinationDictionary nameDestDict = this.GetDests();
if ((nameDestDict != default!)) {
string name = namedDest.GetNamedDestination();
pageDestination = (global::DripSharp.PdfCarton.Pdmodel.Interactive.Documentnavigation.Destination.PDPageDestination)(nameDestDict.GetDestination(name)!);
}
}
return pageDestination!;
}

public virtual void SetNames(global::DripSharp.PdfCarton.Pdmodel.PDDocumentNameDictionary names) {
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.Names, names);
}

public virtual global::DripSharp.PdfCarton.Pdmodel.Documentinterchange.Logicalstructure.PDMarkInfo GetMarkInfo() {
global::DripSharp.PdfCarton.Cos.COSDictionary dic = this.root.GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName.MarkInfo);
return ((dic == default!) ? (global::DripSharp.PdfCarton.Pdmodel.Documentinterchange.Logicalstructure.PDMarkInfo)(default!) : new global::DripSharp.PdfCarton.Pdmodel.Documentinterchange.Logicalstructure.PDMarkInfo(dic));
}

public virtual void SetMarkInfo(global::DripSharp.PdfCarton.Pdmodel.Documentinterchange.Logicalstructure.PDMarkInfo markInfo) {
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.MarkInfo, markInfo);
}

public virtual global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDOutputIntent> GetOutputIntents() {
global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDOutputIntent> retval;
global::DripSharp.PdfCarton.Cos.COSArray array = this.root.GetCOSArray(global::DripSharp.PdfCarton.Cos.COSName.OutputIntents);
if ((array != default!)) {
retval = new global::System.Collections.Generic.List<global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDOutputIntent>(array.Size());
foreach (global::DripSharp.PdfCarton.Cos.COSBase __foreachValue_cosBase in array) {
global::DripSharp.PdfCarton.Cos.COSBase cosBase = __foreachValue_cosBase;
{
if ((cosBase is global::DripSharp.PdfCarton.Cos.COSObject)) {
cosBase = ((global::DripSharp.PdfCarton.Cos.COSObject)(cosBase!)).GetObject();
}
global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDOutputIntent oi = new global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDOutputIntent((global::DripSharp.PdfCarton.Cos.COSDictionary)(cosBase!));
global::DripSharp.Runtime.JavaCompat.Add(retval, oi);
}
}
} else {
retval = new global::System.Collections.Generic.List<global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDOutputIntent>();
}
return retval;
}

public virtual void AddOutputIntent(global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDOutputIntent outputIntent) {
global::DripSharp.PdfCarton.Cos.COSArray array = this.root.GetCOSArray(global::DripSharp.PdfCarton.Cos.COSName.OutputIntents);
if ((array == default!)) {
array = new global::DripSharp.PdfCarton.Cos.COSArray();
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.OutputIntents, array);
}
array.Add(outputIntent.GetCOSObject());
}

public virtual void SetOutputIntents(global::System.Collections.Generic.IList<global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDOutputIntent> outputIntents) {
global::DripSharp.PdfCarton.Cos.COSArray array = new global::DripSharp.PdfCarton.Cos.COSArray();
foreach (global::DripSharp.PdfCarton.Pdmodel.Graphics.Color.PDOutputIntent intent in outputIntents) {
array.Add(intent.GetCOSObject());
}
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.OutputIntents, array);
}

public virtual global::DripSharp.PdfCarton.Pdmodel.PageMode GetPageMode() {
string mode = this.root.GetNameAsString(global::DripSharp.PdfCarton.Cos.COSName.PageMode);
if ((mode != default!)) {
try {
return global::DripSharp.PdfCarton.Pdmodel.PageMode.FromString(mode);
} catch (global::System.ArgumentException e) {
global::Microsoft.Extensions.Logging.LoggerExtensions.LogDebug(global::DripSharp.PdfCarton.Pdmodel.PDDocumentCatalog.LOG, (global::System.Exception)e, global::DripSharp.Runtime.JavaCompat.StringValueOf(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("Invalid PageMode used '", mode), "' - setting to PageMode.USE_NONE")));
return global::DripSharp.PdfCarton.Pdmodel.PageMode.UseNone;
}
} else {
return global::DripSharp.PdfCarton.Pdmodel.PageMode.UseNone;
}
}

public virtual void SetPageMode(global::DripSharp.PdfCarton.Pdmodel.PageMode mode) {
this.root.SetName(global::DripSharp.PdfCarton.Cos.COSName.PageMode, mode.StringValue());
}

public virtual global::DripSharp.PdfCarton.Pdmodel.PageLayout GetPageLayout() {
string mode = this.root.GetNameAsString(global::DripSharp.PdfCarton.Cos.COSName.PageLayout);
if (((mode != default!) && !((mode.Length == 0)))) {
try {
return global::DripSharp.PdfCarton.Pdmodel.PageLayout.FromString(mode);
} catch (global::System.ArgumentException e) {
global::Microsoft.Extensions.Logging.LoggerExtensions.LogWarning(global::DripSharp.PdfCarton.Pdmodel.PDDocumentCatalog.LOG, (global::System.Exception)e, global::DripSharp.Runtime.JavaCompat.StringValueOf(global::DripSharp.Runtime.JavaCompat.Concat(global::DripSharp.Runtime.JavaCompat.Concat("Invalid PageLayout used '", mode), "' - returning PageLayout.SINGLE_PAGE")));
}
}
return global::DripSharp.PdfCarton.Pdmodel.PageLayout.SinglePage;
}

public virtual void SetPageLayout(global::DripSharp.PdfCarton.Pdmodel.PageLayout layout) {
this.root.SetName(global::DripSharp.PdfCarton.Cos.COSName.PageLayout, layout.StringValue());
}

public virtual global::DripSharp.PdfCarton.Pdmodel.Interactive.Action.PDURIDictionary GetURI() {
global::DripSharp.PdfCarton.Cos.COSDictionary uri = this.root.GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName.Uri);
return ((uri == default!) ? (global::DripSharp.PdfCarton.Pdmodel.Interactive.Action.PDURIDictionary)(default!) : new global::DripSharp.PdfCarton.Pdmodel.Interactive.Action.PDURIDictionary(uri));
}

public virtual void SetURI(global::DripSharp.PdfCarton.Pdmodel.Interactive.Action.PDURIDictionary uri) {
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.Uri, uri);
}

public virtual global::DripSharp.PdfCarton.Pdmodel.Documentinterchange.Logicalstructure.PDStructureTreeRoot GetStructureTreeRoot() {
global::DripSharp.PdfCarton.Cos.COSDictionary dict = this.root.GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName.StructTreeRoot);
return ((dict == default!) ? (global::DripSharp.PdfCarton.Pdmodel.Documentinterchange.Logicalstructure.PDStructureTreeRoot)(default!) : new global::DripSharp.PdfCarton.Pdmodel.Documentinterchange.Logicalstructure.PDStructureTreeRoot(dict));
}

public virtual void SetStructureTreeRoot(global::DripSharp.PdfCarton.Pdmodel.Documentinterchange.Logicalstructure.PDStructureTreeRoot treeRoot) {
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.StructTreeRoot, treeRoot);
}

public virtual string GetLanguage() {
return this.root.GetString(global::DripSharp.PdfCarton.Cos.COSName.Lang);
}

public virtual void SetLanguage(string language) {
this.root.SetString(global::DripSharp.PdfCarton.Cos.COSName.Lang, language);
}

public virtual string GetVersion() {
return this.root.GetNameAsString(global::DripSharp.PdfCarton.Cos.COSName.Version);
}

public virtual void SetVersion(string version) {
this.root.SetName(global::DripSharp.PdfCarton.Cos.COSName.Version, version);
}

public virtual global::DripSharp.PdfCarton.Pdmodel.Common.PDPageLabels GetPageLabels() {
global::DripSharp.PdfCarton.Cos.COSDictionary dict = this.root.GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName.PageLabels);
return ((dict == default!) ? (global::DripSharp.PdfCarton.Pdmodel.Common.PDPageLabels)(default!) : new global::DripSharp.PdfCarton.Pdmodel.Common.PDPageLabels(this.document, dict));
}

public virtual void SetPageLabels(global::DripSharp.PdfCarton.Pdmodel.Common.PDPageLabels labels) {
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.PageLabels, labels);
}

public virtual global::DripSharp.PdfCarton.Pdmodel.Graphics.Optionalcontent.PDOptionalContentProperties GetOCProperties() {
global::DripSharp.PdfCarton.Cos.COSDictionary dict = this.root.GetCOSDictionary(global::DripSharp.PdfCarton.Cos.COSName.Ocproperties);
return ((dict == default!) ? (global::DripSharp.PdfCarton.Pdmodel.Graphics.Optionalcontent.PDOptionalContentProperties)(default!) : new global::DripSharp.PdfCarton.Pdmodel.Graphics.Optionalcontent.PDOptionalContentProperties(dict));
}

public virtual void SetOCProperties(global::DripSharp.PdfCarton.Pdmodel.Graphics.Optionalcontent.PDOptionalContentProperties ocProperties) {
this.root.SetItem(global::DripSharp.PdfCarton.Cos.COSName.Ocproperties, ocProperties);
if (((ocProperties != default!) && (this.document.GetVersion() < 1.5D))) {
this.document.SetVersion(1.5F);
}
}

global::DripSharp.PdfCarton.Cos.COSBase global::DripSharp.PdfCarton.Pdmodel.Common.COSObjectable.GetCOSObject() => (global::DripSharp.PdfCarton.Cos.COSBase)(this.GetCOSObject());
}
